package online.shixun.demo.eshop.module.activity.mapper;

import java.util.List;
import online.shixun.demo.eshop.dto.EshopActivity;
import online.shixun.demo.eshop.dto.EshopActivityCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface EshopActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_activity
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    @SelectProvider(type=EshopActivitySqlProvider.class, method="countByExample")
    long countByExample(EshopActivityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_activity
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    @DeleteProvider(type=EshopActivitySqlProvider.class, method="deleteByExample")
    int deleteByExample(EshopActivityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_activity
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    @Delete({
        "delete from eshop_activity",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_activity
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    @Insert({
        "insert into eshop_activity (id, is_del, ",
        "create_time, update_time, ",
        "activity_name, activity_content, ",
        "activity_start_time, activity_end_time, ",
        "activity_index)",
        "values (#{id,jdbcType=VARCHAR}, #{isDel,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=DATE}, #{updateTime,jdbcType=DATE}, ",
        "#{activityName,jdbcType=VARCHAR}, #{activityContent,jdbcType=VARCHAR}, ",
        "#{activityStartTime,jdbcType=DATE}, #{activityEndTime,jdbcType=DATE}, ",
        "#{activityIndex,jdbcType=INTEGER})"
    })
    int insert(EshopActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_activity
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    @InsertProvider(type=EshopActivitySqlProvider.class, method="insertSelective")
    int insertSelective(EshopActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_activity
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    @SelectProvider(type=EshopActivitySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="is_del", property="isDel", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
        @Result(column="activity_name", property="activityName", jdbcType=JdbcType.VARCHAR),
        @Result(column="activity_content", property="activityContent", jdbcType=JdbcType.VARCHAR),
        @Result(column="activity_start_time", property="activityStartTime", jdbcType=JdbcType.DATE),
        @Result(column="activity_end_time", property="activityEndTime", jdbcType=JdbcType.DATE),
        @Result(column="activity_index", property="activityIndex", jdbcType=JdbcType.INTEGER)
    })
    List<EshopActivity> selectByExample(EshopActivityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_activity
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    @Select({
        "select",
        "id, is_del, create_time, update_time, activity_name, activity_content, activity_start_time, ",
        "activity_end_time, activity_index",
        "from eshop_activity",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="is_del", property="isDel", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
        @Result(column="activity_name", property="activityName", jdbcType=JdbcType.VARCHAR),
        @Result(column="activity_content", property="activityContent", jdbcType=JdbcType.VARCHAR),
        @Result(column="activity_start_time", property="activityStartTime", jdbcType=JdbcType.DATE),
        @Result(column="activity_end_time", property="activityEndTime", jdbcType=JdbcType.DATE),
        @Result(column="activity_index", property="activityIndex", jdbcType=JdbcType.INTEGER)
    })
    EshopActivity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_activity
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    @UpdateProvider(type=EshopActivitySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") EshopActivity record, @Param("example") EshopActivityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_activity
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    @UpdateProvider(type=EshopActivitySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") EshopActivity record, @Param("example") EshopActivityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_activity
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    @UpdateProvider(type=EshopActivitySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(EshopActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_activity
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    @Update({
        "update eshop_activity",
        "set is_del = #{isDel,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=DATE},",
          "update_time = #{updateTime,jdbcType=DATE},",
          "activity_name = #{activityName,jdbcType=VARCHAR},",
          "activity_content = #{activityContent,jdbcType=VARCHAR},",
          "activity_start_time = #{activityStartTime,jdbcType=DATE},",
          "activity_end_time = #{activityEndTime,jdbcType=DATE},",
          "activity_index = #{activityIndex,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(EshopActivity record);
}