package online.shixun.demo.eshop.module.collect.mapper;

import java.util.List;
import online.shixun.demo.eshop.dto.EshopCollect;
import online.shixun.demo.eshop.dto.EshopCollectCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface EshopCollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_collect
     *
     * @mbg.generated Tue May 15 16:17:45 CST 2018
     */
    @SelectProvider(type=EshopCollectSqlProvider.class, method="countByExample")
    long countByExample(EshopCollectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_collect
     *
     * @mbg.generated Tue May 15 16:17:45 CST 2018
     */
    @DeleteProvider(type=EshopCollectSqlProvider.class, method="deleteByExample")
    int deleteByExample(EshopCollectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_collect
     *
     * @mbg.generated Tue May 15 16:17:45 CST 2018
     */
    @Delete({
        "delete from eshop_collect",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_collect
     *
     * @mbg.generated Tue May 15 16:17:45 CST 2018
     */
    @Insert({
        "insert into eshop_collect (id, is_del, ",
        "create_time, update_time, ",
        "user_id, collect_name, ",
        "collect_number, collect_viewcount)",
        "values (#{id,jdbcType=VARCHAR}, #{isDel,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=DATE}, #{updateTime,jdbcType=DATE}, ",
        "#{userId,jdbcType=VARCHAR}, #{collectName,jdbcType=VARCHAR}, ",
        "#{collectNumber,jdbcType=INTEGER}, #{collectViewcount,jdbcType=INTEGER})"
    })
    int insert(EshopCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_collect
     *
     * @mbg.generated Tue May 15 16:17:45 CST 2018
     */
    @InsertProvider(type=EshopCollectSqlProvider.class, method="insertSelective")
    int insertSelective(EshopCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_collect
     *
     * @mbg.generated Tue May 15 16:17:45 CST 2018
     */
    @SelectProvider(type=EshopCollectSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="is_del", property="isDel", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="collect_name", property="collectName", jdbcType=JdbcType.VARCHAR),
        @Result(column="collect_number", property="collectNumber", jdbcType=JdbcType.INTEGER),
        @Result(column="collect_viewcount", property="collectViewcount", jdbcType=JdbcType.INTEGER)
    })
    List<EshopCollect> selectByExample(EshopCollectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_collect
     *
     * @mbg.generated Tue May 15 16:17:45 CST 2018
     */
    @Select({
        "select",
        "id, is_del, create_time, update_time, user_id, collect_name, collect_number, ",
        "collect_viewcount",
        "from eshop_collect",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="is_del", property="isDel", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="collect_name", property="collectName", jdbcType=JdbcType.VARCHAR),
        @Result(column="collect_number", property="collectNumber", jdbcType=JdbcType.INTEGER),
        @Result(column="collect_viewcount", property="collectViewcount", jdbcType=JdbcType.INTEGER)
    })
    EshopCollect selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_collect
     *
     * @mbg.generated Tue May 15 16:17:45 CST 2018
     */
    @UpdateProvider(type=EshopCollectSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") EshopCollect record, @Param("example") EshopCollectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_collect
     *
     * @mbg.generated Tue May 15 16:17:45 CST 2018
     */
    @UpdateProvider(type=EshopCollectSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") EshopCollect record, @Param("example") EshopCollectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_collect
     *
     * @mbg.generated Tue May 15 16:17:45 CST 2018
     */
    @UpdateProvider(type=EshopCollectSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(EshopCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_collect
     *
     * @mbg.generated Tue May 15 16:17:45 CST 2018
     */
    @Update({
        "update eshop_collect",
        "set is_del = #{isDel,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=DATE},",
          "update_time = #{updateTime,jdbcType=DATE},",
          "user_id = #{userId,jdbcType=VARCHAR},",
          "collect_name = #{collectName,jdbcType=VARCHAR},",
          "collect_number = #{collectNumber,jdbcType=INTEGER},",
          "collect_viewcount = #{collectViewcount,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(EshopCollect record);
}