package online.shixun.demo.eshop.module.product.mapper;

import java.util.List;
import online.shixun.demo.eshop.dto.EshopImg;
import online.shixun.demo.eshop.dto.EshopImgCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
@Mapper
public interface EshopImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_img
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    @SelectProvider(type=EshopImgSqlProvider.class, method="countByExample")
    long countByExample(EshopImgCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_img
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    @DeleteProvider(type=EshopImgSqlProvider.class, method="deleteByExample")
    int deleteByExample(EshopImgCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_img
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    @Delete({
        "delete from eshop_img",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_img
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    @Insert({
        "insert into eshop_img (id, is_del, ",
        "create_time, update_time, ",
        "img_url, img_is_def, ",
        "img_name, product_id)",
        "values (#{id,jdbcType=VARCHAR}, #{isDel,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=DATE}, #{updateTime,jdbcType=DATE}, ",
        "#{imgUrl,jdbcType=VARCHAR}, #{imgIsDef,jdbcType=INTEGER}, ",
        "#{imgName,jdbcType=VARCHAR}, #{productId,jdbcType=VARCHAR})"
    })
    int insert(EshopImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_img
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    @InsertProvider(type=EshopImgSqlProvider.class, method="insertSelective")
    int insertSelective(EshopImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_img
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    @SelectProvider(type=EshopImgSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="is_del", property="isDel", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
        @Result(column="img_url", property="imgUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="img_is_def", property="imgIsDef", jdbcType=JdbcType.INTEGER),
        @Result(column="img_name", property="imgName", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_id", property="productId", jdbcType=JdbcType.VARCHAR)
    })
    List<EshopImg> selectByExample(EshopImgCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_img
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    @Select({
        "select",
        "id, is_del, create_time, update_time, img_url, img_is_def, img_name, product_id",
        "from eshop_img",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="is_del", property="isDel", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
        @Result(column="img_url", property="imgUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="img_is_def", property="imgIsDef", jdbcType=JdbcType.INTEGER),
        @Result(column="img_name", property="imgName", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_id", property="productId", jdbcType=JdbcType.VARCHAR)
    })
    EshopImg selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_img
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    @UpdateProvider(type=EshopImgSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") EshopImg record, @Param("example") EshopImgCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_img
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    @UpdateProvider(type=EshopImgSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") EshopImg record, @Param("example") EshopImgCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_img
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    @UpdateProvider(type=EshopImgSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(EshopImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_img
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    @Update({
        "update eshop_img",
        "set is_del = #{isDel,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=DATE},",
          "update_time = #{updateTime,jdbcType=DATE},",
          "img_url = #{imgUrl,jdbcType=VARCHAR},",
          "img_is_def = #{imgIsDef,jdbcType=INTEGER},",
          "img_name = #{imgName,jdbcType=VARCHAR},",
          "product_id = #{productId,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(EshopImg record);
}