package online.shixun.demo.eshop.module.product.mapper;

import java.util.Collection;
import java.util.List;
import online.shixun.demo.eshop.dto.EshopFeature;
import online.shixun.demo.eshop.dto.EshopFeatureCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface EshopFeatureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_feature
     *
     * @mbg.generated Fri May 11 10:31:52 CST 2018
     */
    @SelectProvider(type=EshopFeatureSqlProvider.class, method="countByExample")
    long countByExample(EshopFeatureCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_feature
     *
     * @mbg.generated Fri May 11 10:31:52 CST 2018
     */
    @DeleteProvider(type=EshopFeatureSqlProvider.class, method="deleteByExample")
    int deleteByExample(EshopFeatureCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_feature
     *
     * @mbg.generated Fri May 11 10:31:52 CST 2018
     */
    @Delete({
        "delete from eshop_feature",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_feature
     *
     * @mbg.generated Fri May 11 10:31:52 CST 2018
     */
    @Insert({
        "insert into eshop_feature (id, is_del, ",
        "create_time, update_time, ",
        "feature_name, feature_value, ",
        "feature_index)",
        "values (#{id,jdbcType=VARCHAR}, #{isDel,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=DATE}, #{updateTime,jdbcType=DATE}, ",
        "#{featureName,jdbcType=VARCHAR}, #{featureValue,jdbcType=VARCHAR}, ",
        "#{featureIndex,jdbcType=INTEGER})"
    })
    int insert(EshopFeature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_feature
     *
     * @mbg.generated Fri May 11 10:31:52 CST 2018
     */
    @InsertProvider(type=EshopFeatureSqlProvider.class, method="insertSelective")
    int insertSelective(EshopFeature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_feature
     *
     * @mbg.generated Fri May 11 10:31:52 CST 2018
     */
    @SelectProvider(type=EshopFeatureSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="is_del", property="isDel", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
        @Result(column="feature_name", property="featureName", jdbcType=JdbcType.VARCHAR),
        @Result(column="feature_value", property="featureValue", jdbcType=JdbcType.VARCHAR),
        @Result(column="feature_index", property="featureIndex", jdbcType=JdbcType.INTEGER)
    })
    List<EshopFeature> selectByExample(EshopFeatureCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_feature
     *
     * @mbg.generated Fri May 11 10:31:52 CST 2018
     */
    @Select({
        "select",
        "id, is_del, create_time, update_time, feature_name, feature_value, feature_index",
        "from eshop_feature",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="is_del", property="isDel", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
        @Result(column="feature_name", property="featureName", jdbcType=JdbcType.VARCHAR),
        @Result(column="feature_value", property="featureValue", jdbcType=JdbcType.VARCHAR),
        @Result(column="feature_index", property="featureIndex", jdbcType=JdbcType.INTEGER)
    })
    EshopFeature selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_feature
     *
     * @mbg.generated Fri May 11 10:31:52 CST 2018
     */
    @UpdateProvider(type=EshopFeatureSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") EshopFeature record, @Param("example") EshopFeatureCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_feature
     *
     * @mbg.generated Fri May 11 10:31:52 CST 2018
     */
    @UpdateProvider(type=EshopFeatureSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") EshopFeature record, @Param("example") EshopFeatureCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_feature
     *
     * @mbg.generated Fri May 11 10:31:52 CST 2018
     */
    @UpdateProvider(type=EshopFeatureSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(EshopFeature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_feature
     *
     * @mbg.generated Fri May 11 10:31:52 CST 2018
     */
    @Update({
        "update eshop_feature",
        "set is_del = #{isDel,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=DATE},",
          "update_time = #{updateTime,jdbcType=DATE},",
          "feature_name = #{featureName,jdbcType=VARCHAR},",
          "feature_value = #{featureValue,jdbcType=VARCHAR},",
          "feature_index = #{featureIndex,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(EshopFeature record);

    @Results({
            @Result(column = "id", property = "id", jdbcType = JdbcType.VARCHAR, id = true),
            @Result(column = "is_del", property = "isDel", jdbcType = JdbcType.INTEGER),
            @Result(column = "create_time", property = "createTime", jdbcType = JdbcType.DATE),
            @Result(column = "update_time", property = "updateTime", jdbcType = JdbcType.DATE),
            @Result(column = "feature_name", property = "featureName", jdbcType = JdbcType.VARCHAR),
            @Result(column = "feature_value", property = "featureValue", jdbcType = JdbcType.VARCHAR),
            @Result(column = "feature_index", property = "featureIndex", jdbcType = JdbcType.INTEGER)
    })
    @Select(value = {
            "<script>",
            "select * from eshop_feature where is_del=2 ",
            "<foreach collection='list' index='index' item='item' open='and id in (' separator=',' close=')'>",
            "#{item}",
            "</foreach>",
            "</script>"
    })
    List<EshopFeature> getEshopFeaturesByIds(Collection<String> ids);
}