package online.shixun.demo.eshop.module.address.mapper;

import java.util.List;
import online.shixun.demo.eshop.dto.EshopAddressTown;
import online.shixun.demo.eshop.dto.EshopAddressTownCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface EshopAddressTownMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address_town
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    @SelectProvider(type=EshopAddressTownSqlProvider.class, method="countByExample")
    long countByExample(EshopAddressTownCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address_town
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    @DeleteProvider(type=EshopAddressTownSqlProvider.class, method="deleteByExample")
    int deleteByExample(EshopAddressTownCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address_town
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    @Delete({
        "delete from eshop_address_town",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address_town
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    @Insert({
        "insert into eshop_address_town (id, is_del, ",
        "create_time, update_time, ",
        "code, name, city_code)",
        "values (#{id,jdbcType=VARCHAR}, #{isDel,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=DATE}, #{updateTime,jdbcType=DATE}, ",
        "#{code,jdbcType=CHAR}, #{name,jdbcType=VARCHAR}, #{cityCode,jdbcType=CHAR})"
    })
    int insert(EshopAddressTown record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address_town
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    @InsertProvider(type=EshopAddressTownSqlProvider.class, method="insertSelective")
    int insertSelective(EshopAddressTown record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address_town
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    @SelectProvider(type=EshopAddressTownSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="is_del", property="isDel", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
        @Result(column="code", property="code", jdbcType=JdbcType.CHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="city_code", property="cityCode", jdbcType=JdbcType.CHAR)
    })
    List<EshopAddressTown> selectByExample(EshopAddressTownCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address_town
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    @Select({
        "select",
        "id, is_del, create_time, update_time, code, name, city_code",
        "from eshop_address_town",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="is_del", property="isDel", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
        @Result(column="code", property="code", jdbcType=JdbcType.CHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="city_code", property="cityCode", jdbcType=JdbcType.CHAR)
    })
    EshopAddressTown selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address_town
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    @UpdateProvider(type=EshopAddressTownSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") EshopAddressTown record, @Param("example") EshopAddressTownCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address_town
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    @UpdateProvider(type=EshopAddressTownSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") EshopAddressTown record, @Param("example") EshopAddressTownCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address_town
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    @UpdateProvider(type=EshopAddressTownSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(EshopAddressTown record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address_town
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    @Update({
        "update eshop_address_town",
        "set is_del = #{isDel,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=DATE},",
          "update_time = #{updateTime,jdbcType=DATE},",
          "code = #{code,jdbcType=CHAR},",
          "name = #{name,jdbcType=VARCHAR},",
          "city_code = #{cityCode,jdbcType=CHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(EshopAddressTown record);
}