package online.shixun.demo.eshop.module.address.mapper;

import java.util.List;
import online.shixun.demo.eshop.dto.EshopAddressCity;
import online.shixun.demo.eshop.dto.EshopAddressCityCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface EshopAddressCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address_city
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    @SelectProvider(type=EshopAddressCitySqlProvider.class, method="countByExample")
    long countByExample(EshopAddressCityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address_city
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    @DeleteProvider(type=EshopAddressCitySqlProvider.class, method="deleteByExample")
    int deleteByExample(EshopAddressCityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address_city
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    @Delete({
        "delete from eshop_address_city",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address_city
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    @Insert({
        "insert into eshop_address_city (id, is_del, ",
        "create_time, update_time, ",
        "code, name, province_code)",
        "values (#{id,jdbcType=VARCHAR}, #{isDel,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=DATE}, #{updateTime,jdbcType=DATE}, ",
        "#{code,jdbcType=CHAR}, #{name,jdbcType=VARCHAR}, #{provinceCode,jdbcType=CHAR})"
    })
    int insert(EshopAddressCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address_city
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    @InsertProvider(type=EshopAddressCitySqlProvider.class, method="insertSelective")
    int insertSelective(EshopAddressCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address_city
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    @SelectProvider(type=EshopAddressCitySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="is_del", property="isDel", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
        @Result(column="code", property="code", jdbcType=JdbcType.CHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="province_code", property="provinceCode", jdbcType=JdbcType.CHAR)
    })
    List<EshopAddressCity> selectByExample(EshopAddressCityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address_city
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    @Select({
        "select",
        "id, is_del, create_time, update_time, code, name, province_code",
        "from eshop_address_city",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="is_del", property="isDel", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
        @Result(column="code", property="code", jdbcType=JdbcType.CHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="province_code", property="provinceCode", jdbcType=JdbcType.CHAR)
    })
    EshopAddressCity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address_city
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    @UpdateProvider(type=EshopAddressCitySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") EshopAddressCity record, @Param("example") EshopAddressCityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address_city
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    @UpdateProvider(type=EshopAddressCitySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") EshopAddressCity record, @Param("example") EshopAddressCityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address_city
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    @UpdateProvider(type=EshopAddressCitySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(EshopAddressCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address_city
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    @Update({
        "update eshop_address_city",
        "set is_del = #{isDel,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=DATE},",
          "update_time = #{updateTime,jdbcType=DATE},",
          "code = #{code,jdbcType=CHAR},",
          "name = #{name,jdbcType=VARCHAR},",
          "province_code = #{provinceCode,jdbcType=CHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(EshopAddressCity record);
}