package online.shixun.demo.eshop.module.address.mapper;

import java.util.List;
import online.shixun.demo.eshop.dto.EshopAddressState;
import online.shixun.demo.eshop.dto.EshopAddressStateCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface EshopAddressStateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address_state
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    @SelectProvider(type=EshopAddressStateSqlProvider.class, method="countByExample")
    long countByExample(EshopAddressStateCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address_state
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    @DeleteProvider(type=EshopAddressStateSqlProvider.class, method="deleteByExample")
    int deleteByExample(EshopAddressStateCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address_state
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    @Delete({
        "delete from eshop_address_state",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address_state
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    @Insert({
        "insert into eshop_address_state (id, is_del, ",
        "create_time, update_time, ",
        "code, name)",
        "values (#{id,jdbcType=VARCHAR}, #{isDel,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=DATE}, #{updateTime,jdbcType=DATE}, ",
        "#{code,jdbcType=CHAR}, #{name,jdbcType=VARCHAR})"
    })
    int insert(EshopAddressState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address_state
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    @InsertProvider(type=EshopAddressStateSqlProvider.class, method="insertSelective")
    int insertSelective(EshopAddressState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address_state
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    @SelectProvider(type=EshopAddressStateSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="is_del", property="isDel", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
        @Result(column="code", property="code", jdbcType=JdbcType.CHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR)
    })
    List<EshopAddressState> selectByExample(EshopAddressStateCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address_state
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    @Select({
        "select",
        "id, is_del, create_time, update_time, code, name",
        "from eshop_address_state",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="is_del", property="isDel", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
        @Result(column="code", property="code", jdbcType=JdbcType.CHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR)
    })
    EshopAddressState selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address_state
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    @UpdateProvider(type=EshopAddressStateSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") EshopAddressState record, @Param("example") EshopAddressStateCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address_state
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    @UpdateProvider(type=EshopAddressStateSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") EshopAddressState record, @Param("example") EshopAddressStateCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address_state
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    @UpdateProvider(type=EshopAddressStateSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(EshopAddressState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address_state
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    @Update({
        "update eshop_address_state",
        "set is_del = #{isDel,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=DATE},",
          "update_time = #{updateTime,jdbcType=DATE},",
          "code = #{code,jdbcType=CHAR},",
          "name = #{name,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(EshopAddressState record);
}