package online.shixun.demo.eshop.module.user.mapper;

import java.util.List;
import java.util.Map;
import online.shixun.demo.eshop.dto.EshopUser;
import online.shixun.demo.eshop.dto.EshopUserCriteria.Criteria;
import online.shixun.demo.eshop.dto.EshopUserCriteria.Criterion;
import online.shixun.demo.eshop.dto.EshopUserCriteria;
import org.apache.ibatis.jdbc.SQL;

public class EshopUserSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_user
     *
     * @mbg.generated Wed May 16 14:30:10 CST 2018
     */
    public String countByExample(EshopUserCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("eshop_user");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_user
     *
     * @mbg.generated Wed May 16 14:30:10 CST 2018
     */
    public String deleteByExample(EshopUserCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("eshop_user");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_user
     *
     * @mbg.generated Wed May 16 14:30:10 CST 2018
     */
    public String insertSelective(EshopUser record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("eshop_user");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=VARCHAR}");
        }
        
        if (record.getIsDel() != null) {
            sql.VALUES("is_del", "#{isDel,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=DATE}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.VALUES("update_time", "#{updateTime,jdbcType=DATE}");
        }
        
        if (record.getUserEmail() != null) {
            sql.VALUES("user_email", "#{userEmail,jdbcType=VARCHAR}");
        }
        
        if (record.getUserLoginName() != null) {
            sql.VALUES("user_login_name", "#{userLoginName,jdbcType=VARCHAR}");
        }
        
        if (record.getUserNicakName() != null) {
            sql.VALUES("user_nicak_name", "#{userNicakName,jdbcType=VARCHAR}");
        }
        
        if (record.getUserPassword() != null) {
            sql.VALUES("user_password", "#{userPassword,jdbcType=VARCHAR}");
        }
        
        if (record.getUserRealName() != null) {
            sql.VALUES("user_real_name", "#{userRealName,jdbcType=VARCHAR}");
        }
        
        if (record.getUserGender() != null) {
            sql.VALUES("user_gender", "#{userGender,jdbcType=INTEGER}");
        }
        
        if (record.getUserDescription() != null) {
            sql.VALUES("user_description", "#{userDescription,jdbcType=VARCHAR}");
        }
        
        if (record.getUserImage() != null) {
            sql.VALUES("user_image", "#{userImage,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_user
     *
     * @mbg.generated Wed May 16 14:30:10 CST 2018
     */
    public String selectByExample(EshopUserCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("is_del");
        sql.SELECT("create_time");
        sql.SELECT("update_time");
        sql.SELECT("user_email");
        sql.SELECT("user_login_name");
        sql.SELECT("user_nicak_name");
        sql.SELECT("user_password");
        sql.SELECT("user_real_name");
        sql.SELECT("user_gender");
        sql.SELECT("user_description");
        sql.SELECT("user_image");
        sql.FROM("eshop_user");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_user
     *
     * @mbg.generated Wed May 16 14:30:10 CST 2018
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        EshopUser record = (EshopUser) parameter.get("record");
        EshopUserCriteria example = (EshopUserCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("eshop_user");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        }
        
        if (record.getIsDel() != null) {
            sql.SET("is_del = #{record.isDel,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{record.createTime,jdbcType=DATE}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{record.updateTime,jdbcType=DATE}");
        }
        
        if (record.getUserEmail() != null) {
            sql.SET("user_email = #{record.userEmail,jdbcType=VARCHAR}");
        }
        
        if (record.getUserLoginName() != null) {
            sql.SET("user_login_name = #{record.userLoginName,jdbcType=VARCHAR}");
        }
        
        if (record.getUserNicakName() != null) {
            sql.SET("user_nicak_name = #{record.userNicakName,jdbcType=VARCHAR}");
        }
        
        if (record.getUserPassword() != null) {
            sql.SET("user_password = #{record.userPassword,jdbcType=VARCHAR}");
        }
        
        if (record.getUserRealName() != null) {
            sql.SET("user_real_name = #{record.userRealName,jdbcType=VARCHAR}");
        }
        
        if (record.getUserGender() != null) {
            sql.SET("user_gender = #{record.userGender,jdbcType=INTEGER}");
        }
        
        if (record.getUserDescription() != null) {
            sql.SET("user_description = #{record.userDescription,jdbcType=VARCHAR}");
        }
        
        if (record.getUserImage() != null) {
            sql.SET("user_image = #{record.userImage,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_user
     *
     * @mbg.generated Wed May 16 14:30:10 CST 2018
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("eshop_user");
        
        sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        sql.SET("is_del = #{record.isDel,jdbcType=INTEGER}");
        sql.SET("create_time = #{record.createTime,jdbcType=DATE}");
        sql.SET("update_time = #{record.updateTime,jdbcType=DATE}");
        sql.SET("user_email = #{record.userEmail,jdbcType=VARCHAR}");
        sql.SET("user_login_name = #{record.userLoginName,jdbcType=VARCHAR}");
        sql.SET("user_nicak_name = #{record.userNicakName,jdbcType=VARCHAR}");
        sql.SET("user_password = #{record.userPassword,jdbcType=VARCHAR}");
        sql.SET("user_real_name = #{record.userRealName,jdbcType=VARCHAR}");
        sql.SET("user_gender = #{record.userGender,jdbcType=INTEGER}");
        sql.SET("user_description = #{record.userDescription,jdbcType=VARCHAR}");
        sql.SET("user_image = #{record.userImage,jdbcType=VARCHAR}");
        
        EshopUserCriteria example = (EshopUserCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_user
     *
     * @mbg.generated Wed May 16 14:30:10 CST 2018
     */
    public String updateByPrimaryKeySelective(EshopUser record) {
        SQL sql = new SQL();
        sql.UPDATE("eshop_user");
        
        if (record.getIsDel() != null) {
            sql.SET("is_del = #{isDel,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=DATE}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{updateTime,jdbcType=DATE}");
        }
        
        if (record.getUserEmail() != null) {
            sql.SET("user_email = #{userEmail,jdbcType=VARCHAR}");
        }
        
        if (record.getUserLoginName() != null) {
            sql.SET("user_login_name = #{userLoginName,jdbcType=VARCHAR}");
        }
        
        if (record.getUserNicakName() != null) {
            sql.SET("user_nicak_name = #{userNicakName,jdbcType=VARCHAR}");
        }
        
        if (record.getUserPassword() != null) {
            sql.SET("user_password = #{userPassword,jdbcType=VARCHAR}");
        }
        
        if (record.getUserRealName() != null) {
            sql.SET("user_real_name = #{userRealName,jdbcType=VARCHAR}");
        }
        
        if (record.getUserGender() != null) {
            sql.SET("user_gender = #{userGender,jdbcType=INTEGER}");
        }
        
        if (record.getUserDescription() != null) {
            sql.SET("user_description = #{userDescription,jdbcType=VARCHAR}");
        }
        
        if (record.getUserImage() != null) {
            sql.SET("user_image = #{userImage,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_user
     *
     * @mbg.generated Wed May 16 14:30:10 CST 2018
     */
    protected void applyWhere(SQL sql, EshopUserCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}