package online.shixun.demo.eshop.module.about.mapper;

import java.util.List;
import online.shixun.demo.eshop.dto.EshopAbout;
import online.shixun.demo.eshop.dto.EshopAboutCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface EshopAboutMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_about
     *
     * @mbg.generated Mon May 21 14:34:29 CST 2018
     */
    @SelectProvider(type=EshopAboutSqlProvider.class, method="countByExample")
    long countByExample(EshopAboutCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_about
     *
     * @mbg.generated Mon May 21 14:34:29 CST 2018
     */
    @DeleteProvider(type=EshopAboutSqlProvider.class, method="deleteByExample")
    int deleteByExample(EshopAboutCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_about
     *
     * @mbg.generated Mon May 21 14:34:29 CST 2018
     */
    @Delete({
        "delete from eshop_about",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_about
     *
     * @mbg.generated Mon May 21 14:34:29 CST 2018
     */
    @Insert({
        "insert into eshop_about (id, is_del, ",
        "create_time, update_time, ",
        "about_title, about_index, ",
        "about_content)",
        "values (#{id,jdbcType=VARCHAR}, #{isDel,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=DATE}, #{updateTime,jdbcType=DATE}, ",
        "#{aboutTitle,jdbcType=VARCHAR}, #{aboutIndex,jdbcType=INTEGER}, ",
        "#{aboutContent,jdbcType=LONGVARCHAR})"
    })
    int insert(EshopAbout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_about
     *
     * @mbg.generated Mon May 21 14:34:29 CST 2018
     */
    @InsertProvider(type=EshopAboutSqlProvider.class, method="insertSelective")
    int insertSelective(EshopAbout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_about
     *
     * @mbg.generated Mon May 21 14:34:29 CST 2018
     */
    @SelectProvider(type=EshopAboutSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="is_del", property="isDel", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
        @Result(column="about_title", property="aboutTitle", jdbcType=JdbcType.VARCHAR),
        @Result(column="about_index", property="aboutIndex", jdbcType=JdbcType.INTEGER),
        @Result(column="about_content", property="aboutContent", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<EshopAbout> selectByExampleWithBLOBs(EshopAboutCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_about
     *
     * @mbg.generated Mon May 21 14:34:29 CST 2018
     */
    @SelectProvider(type=EshopAboutSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="is_del", property="isDel", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
        @Result(column="about_title", property="aboutTitle", jdbcType=JdbcType.VARCHAR),
        @Result(column="about_index", property="aboutIndex", jdbcType=JdbcType.INTEGER)
    })
    List<EshopAbout> selectByExample(EshopAboutCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_about
     *
     * @mbg.generated Mon May 21 14:34:29 CST 2018
     */
    @Select({
        "select",
        "id, is_del, create_time, update_time, about_title, about_index, about_content",
        "from eshop_about",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="is_del", property="isDel", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
        @Result(column="about_title", property="aboutTitle", jdbcType=JdbcType.VARCHAR),
        @Result(column="about_index", property="aboutIndex", jdbcType=JdbcType.INTEGER),
        @Result(column="about_content", property="aboutContent", jdbcType=JdbcType.LONGVARCHAR)
    })
    EshopAbout selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_about
     *
     * @mbg.generated Mon May 21 14:34:29 CST 2018
     */
    @UpdateProvider(type=EshopAboutSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") EshopAbout record, @Param("example") EshopAboutCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_about
     *
     * @mbg.generated Mon May 21 14:34:29 CST 2018
     */
    @UpdateProvider(type=EshopAboutSqlProvider.class, method="updateByExampleWithBLOBs")
    int updateByExampleWithBLOBs(@Param("record") EshopAbout record, @Param("example") EshopAboutCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_about
     *
     * @mbg.generated Mon May 21 14:34:29 CST 2018
     */
    @UpdateProvider(type=EshopAboutSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") EshopAbout record, @Param("example") EshopAboutCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_about
     *
     * @mbg.generated Mon May 21 14:34:29 CST 2018
     */
    @UpdateProvider(type=EshopAboutSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(EshopAbout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_about
     *
     * @mbg.generated Mon May 21 14:34:29 CST 2018
     */
    @Update({
        "update eshop_about",
        "set is_del = #{isDel,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=DATE},",
          "update_time = #{updateTime,jdbcType=DATE},",
          "about_title = #{aboutTitle,jdbcType=VARCHAR},",
          "about_index = #{aboutIndex,jdbcType=INTEGER},",
          "about_content = #{aboutContent,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKeyWithBLOBs(EshopAbout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_about
     *
     * @mbg.generated Mon May 21 14:34:29 CST 2018
     */
    @Update({
        "update eshop_about",
        "set is_del = #{isDel,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=DATE},",
          "update_time = #{updateTime,jdbcType=DATE},",
          "about_title = #{aboutTitle,jdbcType=VARCHAR},",
          "about_index = #{aboutIndex,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(EshopAbout record);
}