package online.shixun.demo.eshop.dto;

import java.io.Serializable;
import java.util.Date;

public class EshopFeature implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_feature.id
     *
     * @mbg.generated Fri May 11 10:31:52 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_feature.is_del
     *
     * @mbg.generated Fri May 11 10:31:52 CST 2018
     */
    private Integer isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_feature.create_time
     *
     * @mbg.generated Fri May 11 10:31:52 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_feature.update_time
     *
     * @mbg.generated Fri May 11 10:31:52 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_feature.feature_name
     *
     * @mbg.generated Fri May 11 10:31:52 CST 2018
     */
    private String featureName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_feature.feature_value
     *
     * @mbg.generated Fri May 11 10:31:52 CST 2018
     */
    private String featureValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_feature.feature_index
     *
     * @mbg.generated Fri May 11 10:31:52 CST 2018
     */
    private Integer featureIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eshop_feature
     *
     * @mbg.generated Fri May 11 10:31:52 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_feature.id
     *
     * @return the value of eshop_feature.id
     *
     * @mbg.generated Fri May 11 10:31:52 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_feature.id
     *
     * @param id the value for eshop_feature.id
     *
     * @mbg.generated Fri May 11 10:31:52 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_feature.is_del
     *
     * @return the value of eshop_feature.is_del
     *
     * @mbg.generated Fri May 11 10:31:52 CST 2018
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_feature.is_del
     *
     * @param isDel the value for eshop_feature.is_del
     *
     * @mbg.generated Fri May 11 10:31:52 CST 2018
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_feature.create_time
     *
     * @return the value of eshop_feature.create_time
     *
     * @mbg.generated Fri May 11 10:31:52 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_feature.create_time
     *
     * @param createTime the value for eshop_feature.create_time
     *
     * @mbg.generated Fri May 11 10:31:52 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_feature.update_time
     *
     * @return the value of eshop_feature.update_time
     *
     * @mbg.generated Fri May 11 10:31:52 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_feature.update_time
     *
     * @param updateTime the value for eshop_feature.update_time
     *
     * @mbg.generated Fri May 11 10:31:52 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_feature.feature_name
     *
     * @return the value of eshop_feature.feature_name
     *
     * @mbg.generated Fri May 11 10:31:52 CST 2018
     */
    public String getFeatureName() {
        return featureName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_feature.feature_name
     *
     * @param featureName the value for eshop_feature.feature_name
     *
     * @mbg.generated Fri May 11 10:31:52 CST 2018
     */
    public void setFeatureName(String featureName) {
        this.featureName = featureName == null ? null : featureName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_feature.feature_value
     *
     * @return the value of eshop_feature.feature_value
     *
     * @mbg.generated Fri May 11 10:31:52 CST 2018
     */
    public String getFeatureValue() {
        return featureValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_feature.feature_value
     *
     * @param featureValue the value for eshop_feature.feature_value
     *
     * @mbg.generated Fri May 11 10:31:52 CST 2018
     */
    public void setFeatureValue(String featureValue) {
        this.featureValue = featureValue == null ? null : featureValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_feature.feature_index
     *
     * @return the value of eshop_feature.feature_index
     *
     * @mbg.generated Fri May 11 10:31:52 CST 2018
     */
    public Integer getFeatureIndex() {
        return featureIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_feature.feature_index
     *
     * @param featureIndex the value for eshop_feature.feature_index
     *
     * @mbg.generated Fri May 11 10:31:52 CST 2018
     */
    public void setFeatureIndex(Integer featureIndex) {
        this.featureIndex = featureIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_feature
     *
     * @mbg.generated Fri May 11 10:31:52 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", isDel=").append(isDel);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", featureName=").append(featureName);
        sb.append(", featureValue=").append(featureValue);
        sb.append(", featureIndex=").append(featureIndex);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}