package online.shixun.demo.eshop.dto;

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.io.Serializable;
import java.util.Date;

public class EshopBuyerCartItem implements Serializable {
    //SKU对象
    private EshopSku sku;

    //是否有货
    private boolean isHave = true;

    //库存数量
    private Integer stock;

    public EshopSku getSku() {
        return sku;
    }

    public void setSku(EshopSku sku) {
        this.sku = sku;
    }

    public Boolean getIsHave() {
        return isHave;
    }

    public void setIsHave(boolean have) {
        isHave = have;
    }

    public Integer getStock() {
        return stock;
    }

    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * 小计当前商品购买的金额
     *
     * @return
     */
    @JsonIgnore
    public Float getSubtotal() {
        return this.getAmount() * this.getSku().getSkuPrice();
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((sku == null) ? 0 : sku.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (getClass() != obj.getClass()) {
            return false;
        }
        EshopBuyerCartItem other = (EshopBuyerCartItem) obj;
        if (sku != null && other.getSku() != null) {
            if (sku.getId().equals(other.getSku().getId())) {
                return true;
            }
        }
        if (skuId != null && other.skuId != null) {
            if (skuId.equals(other.getSkuId())) {
                return true;
            }
        }
        if (skuId != null && other.getSku() != null) {
            if (skuId.equals(other.getSku().getId())) {
                return true;
            }
        }
        if (sku != null && other.skuId != null) {
            if (sku.getId().equals(other.skuId)) {
                return true;
            }
        }
        return false;
    }
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_buyer_cart_item.id
     *
     * @mbg.generated Wed May 23 17:20:31 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_buyer_cart_item.is_del
     *
     * @mbg.generated Wed May 23 17:20:31 CST 2018
     */
    private Integer isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_buyer_cart_item.create_time
     *
     * @mbg.generated Wed May 23 17:20:31 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_buyer_cart_item.update_time
     *
     * @mbg.generated Wed May 23 17:20:31 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_buyer_cart_item.product_id
     *
     * @mbg.generated Wed May 23 17:20:31 CST 2018
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_buyer_cart_item.sku_id
     *
     * @mbg.generated Wed May 23 17:20:31 CST 2018
     */
    private String skuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_buyer_cart_item.amount
     *
     * @mbg.generated Wed May 23 17:20:31 CST 2018
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_buyer_cart_item.buyer_cart_id
     *
     * @mbg.generated Wed May 23 17:20:31 CST 2018
     */
    private String buyerCartId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eshop_buyer_cart_item
     *
     * @mbg.generated Wed May 23 17:20:31 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_buyer_cart_item.id
     *
     * @return the value of eshop_buyer_cart_item.id
     *
     * @mbg.generated Wed May 23 17:20:31 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_buyer_cart_item.id
     *
     * @param id the value for eshop_buyer_cart_item.id
     *
     * @mbg.generated Wed May 23 17:20:31 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_buyer_cart_item.is_del
     *
     * @return the value of eshop_buyer_cart_item.is_del
     *
     * @mbg.generated Wed May 23 17:20:31 CST 2018
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_buyer_cart_item.is_del
     *
     * @param isDel the value for eshop_buyer_cart_item.is_del
     *
     * @mbg.generated Wed May 23 17:20:31 CST 2018
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_buyer_cart_item.create_time
     *
     * @return the value of eshop_buyer_cart_item.create_time
     *
     * @mbg.generated Wed May 23 17:20:31 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_buyer_cart_item.create_time
     *
     * @param createTime the value for eshop_buyer_cart_item.create_time
     *
     * @mbg.generated Wed May 23 17:20:31 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_buyer_cart_item.update_time
     *
     * @return the value of eshop_buyer_cart_item.update_time
     *
     * @mbg.generated Wed May 23 17:20:31 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_buyer_cart_item.update_time
     *
     * @param updateTime the value for eshop_buyer_cart_item.update_time
     *
     * @mbg.generated Wed May 23 17:20:31 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_buyer_cart_item.product_id
     *
     * @return the value of eshop_buyer_cart_item.product_id
     *
     * @mbg.generated Wed May 23 17:20:31 CST 2018
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_buyer_cart_item.product_id
     *
     * @param productId the value for eshop_buyer_cart_item.product_id
     *
     * @mbg.generated Wed May 23 17:20:31 CST 2018
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_buyer_cart_item.sku_id
     *
     * @return the value of eshop_buyer_cart_item.sku_id
     *
     * @mbg.generated Wed May 23 17:20:31 CST 2018
     */
    public String getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_buyer_cart_item.sku_id
     *
     * @param skuId the value for eshop_buyer_cart_item.sku_id
     *
     * @mbg.generated Wed May 23 17:20:31 CST 2018
     */
    public void setSkuId(String skuId) {
        this.skuId = skuId == null ? null : skuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_buyer_cart_item.amount
     *
     * @return the value of eshop_buyer_cart_item.amount
     *
     * @mbg.generated Wed May 23 17:20:31 CST 2018
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_buyer_cart_item.amount
     *
     * @param amount the value for eshop_buyer_cart_item.amount
     *
     * @mbg.generated Wed May 23 17:20:31 CST 2018
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_buyer_cart_item.buyer_cart_id
     *
     * @return the value of eshop_buyer_cart_item.buyer_cart_id
     *
     * @mbg.generated Wed May 23 17:20:31 CST 2018
     */
    public String getBuyerCartId() {
        return buyerCartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_buyer_cart_item.buyer_cart_id
     *
     * @param buyerCartId the value for eshop_buyer_cart_item.buyer_cart_id
     *
     * @mbg.generated Wed May 23 17:20:31 CST 2018
     */
    public void setBuyerCartId(String buyerCartId) {
        this.buyerCartId = buyerCartId == null ? null : buyerCartId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_buyer_cart_item
     *
     * @mbg.generated Wed May 23 17:20:31 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", isDel=").append(isDel);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", productId=").append(productId);
        sb.append(", skuId=").append(skuId);
        sb.append(", amount=").append(amount);
        sb.append(", buyerCartId=").append(buyerCartId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}