package online.shixun.demo.eshop.dto;

import java.io.Serializable;
import java.util.Date;

public class EshopComment implements Serializable {
    private EshopUser user;

    public EshopUser getUser() {
        return user;
    }

    public void setUser(EshopUser user) {
        this.user = user;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_comment.id
     *
     * @mbg.generated Fri May 11 10:31:09 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_comment.is_del
     *
     * @mbg.generated Fri May 11 10:31:09 CST 2018
     */
    private Integer isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_comment.create_time
     *
     * @mbg.generated Fri May 11 10:31:09 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_comment.update_time
     *
     * @mbg.generated Fri May 11 10:31:09 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_comment.user_id
     *
     * @mbg.generated Fri May 11 10:31:09 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_comment.product_id
     *
     * @mbg.generated Fri May 11 10:31:09 CST 2018
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_comment.common_rank
     *
     * @mbg.generated Fri May 11 10:31:09 CST 2018
     */
    private Float commonRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_comment.common_content
     *
     * @mbg.generated Fri May 11 10:31:09 CST 2018
     */
    private String commonContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eshop_comment
     *
     * @mbg.generated Fri May 11 10:31:09 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_comment.id
     *
     * @return the value of eshop_comment.id
     * @mbg.generated Fri May 11 10:31:09 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_comment.id
     *
     * @param id the value for eshop_comment.id
     * @mbg.generated Fri May 11 10:31:09 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_comment.is_del
     *
     * @return the value of eshop_comment.is_del
     * @mbg.generated Fri May 11 10:31:09 CST 2018
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_comment.is_del
     *
     * @param isDel the value for eshop_comment.is_del
     * @mbg.generated Fri May 11 10:31:09 CST 2018
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_comment.create_time
     *
     * @return the value of eshop_comment.create_time
     * @mbg.generated Fri May 11 10:31:09 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_comment.create_time
     *
     * @param createTime the value for eshop_comment.create_time
     * @mbg.generated Fri May 11 10:31:09 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_comment.update_time
     *
     * @return the value of eshop_comment.update_time
     * @mbg.generated Fri May 11 10:31:09 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_comment.update_time
     *
     * @param updateTime the value for eshop_comment.update_time
     * @mbg.generated Fri May 11 10:31:09 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_comment.user_id
     *
     * @return the value of eshop_comment.user_id
     * @mbg.generated Fri May 11 10:31:09 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_comment.user_id
     *
     * @param userId the value for eshop_comment.user_id
     * @mbg.generated Fri May 11 10:31:09 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_comment.product_id
     *
     * @return the value of eshop_comment.product_id
     * @mbg.generated Fri May 11 10:31:09 CST 2018
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_comment.product_id
     *
     * @param productId the value for eshop_comment.product_id
     * @mbg.generated Fri May 11 10:31:09 CST 2018
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_comment.common_rank
     *
     * @return the value of eshop_comment.common_rank
     * @mbg.generated Fri May 11 10:31:09 CST 2018
     */
    public Float getCommonRank() {
        return commonRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_comment.common_rank
     *
     * @param commonRank the value for eshop_comment.common_rank
     * @mbg.generated Fri May 11 10:31:09 CST 2018
     */
    public void setCommonRank(Float commonRank) {
        this.commonRank = commonRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_comment.common_content
     *
     * @return the value of eshop_comment.common_content
     * @mbg.generated Fri May 11 10:31:09 CST 2018
     */
    public String getCommonContent() {
        return commonContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_comment.common_content
     *
     * @param commonContent the value for eshop_comment.common_content
     * @mbg.generated Fri May 11 10:31:09 CST 2018
     */
    public void setCommonContent(String commonContent) {
        this.commonContent = commonContent == null ? null : commonContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_comment
     *
     * @mbg.generated Fri May 11 10:31:09 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", isDel=").append(isDel);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", userId=").append(userId);
        sb.append(", productId=").append(productId);
        sb.append(", commonRank=").append(commonRank);
        sb.append(", commonContent=").append(commonContent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}