package online.shixun.demo.eshop.dto;

import java.io.Serializable;
import java.util.Date;

public class EshopAddressCity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_address_city.id
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_address_city.is_del
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    private Integer isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_address_city.create_time
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_address_city.update_time
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_address_city.code
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_address_city.name
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_address_city.province_code
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    private String provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eshop_address_city
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_address_city.id
     *
     * @return the value of eshop_address_city.id
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_address_city.id
     *
     * @param id the value for eshop_address_city.id
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_address_city.is_del
     *
     * @return the value of eshop_address_city.is_del
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_address_city.is_del
     *
     * @param isDel the value for eshop_address_city.is_del
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_address_city.create_time
     *
     * @return the value of eshop_address_city.create_time
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_address_city.create_time
     *
     * @param createTime the value for eshop_address_city.create_time
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_address_city.update_time
     *
     * @return the value of eshop_address_city.update_time
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_address_city.update_time
     *
     * @param updateTime the value for eshop_address_city.update_time
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_address_city.code
     *
     * @return the value of eshop_address_city.code
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_address_city.code
     *
     * @param code the value for eshop_address_city.code
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_address_city.name
     *
     * @return the value of eshop_address_city.name
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_address_city.name
     *
     * @param name the value for eshop_address_city.name
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_address_city.province_code
     *
     * @return the value of eshop_address_city.province_code
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_address_city.province_code
     *
     * @param provinceCode the value for eshop_address_city.province_code
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address_city
     *
     * @mbg.generated Wed May 16 14:28:20 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", isDel=").append(isDel);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", code=").append(code);
        sb.append(", name=").append(name);
        sb.append(", provinceCode=").append(provinceCode);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}