package online.shixun.demo.eshop.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class EshopAddressCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eshop_address
     *
     * @mbg.generated Thu May 17 16:36:46 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eshop_address
     *
     * @mbg.generated Thu May 17 16:36:46 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eshop_address
     *
     * @mbg.generated Thu May 17 16:36:46 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address
     *
     * @mbg.generated Thu May 17 16:36:46 CST 2018
     */
    public EshopAddressCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address
     *
     * @mbg.generated Thu May 17 16:36:46 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address
     *
     * @mbg.generated Thu May 17 16:36:46 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address
     *
     * @mbg.generated Thu May 17 16:36:46 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address
     *
     * @mbg.generated Thu May 17 16:36:46 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address
     *
     * @mbg.generated Thu May 17 16:36:46 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address
     *
     * @mbg.generated Thu May 17 16:36:46 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address
     *
     * @mbg.generated Thu May 17 16:36:46 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address
     *
     * @mbg.generated Thu May 17 16:36:46 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address
     *
     * @mbg.generated Thu May 17 16:36:46 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_address
     *
     * @mbg.generated Thu May 17 16:36:46 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table eshop_address
     *
     * @mbg.generated Thu May 17 16:36:46 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNull() {
            addCriterion("is_del is null");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNotNull() {
            addCriterion("is_del is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelEqualTo(Integer value) {
            addCriterion("is_del =", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotEqualTo(Integer value) {
            addCriterion("is_del <>", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThan(Integer value) {
            addCriterion("is_del >", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_del >=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThan(Integer value) {
            addCriterion("is_del <", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThanOrEqualTo(Integer value) {
            addCriterion("is_del <=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelIn(List<Integer> values) {
            addCriterion("is_del in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotIn(List<Integer> values) {
            addCriterion("is_del not in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelBetween(Integer value1, Integer value2) {
            addCriterion("is_del between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotBetween(Integer value1, Integer value2) {
            addCriterion("is_del not between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterionForJDBCDate("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterionForJDBCDate("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterionForJDBCDate("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterionForJDBCDate("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterionForJDBCDate("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterionForJDBCDate("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andStateIdIsNull() {
            addCriterion("state_id is null");
            return (Criteria) this;
        }

        public Criteria andStateIdIsNotNull() {
            addCriterion("state_id is not null");
            return (Criteria) this;
        }

        public Criteria andStateIdEqualTo(String value) {
            addCriterion("state_id =", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdNotEqualTo(String value) {
            addCriterion("state_id <>", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdGreaterThan(String value) {
            addCriterion("state_id >", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdGreaterThanOrEqualTo(String value) {
            addCriterion("state_id >=", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdLessThan(String value) {
            addCriterion("state_id <", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdLessThanOrEqualTo(String value) {
            addCriterion("state_id <=", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdLike(String value) {
            addCriterion("state_id like", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdNotLike(String value) {
            addCriterion("state_id not like", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdIn(List<String> values) {
            addCriterion("state_id in", values, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdNotIn(List<String> values) {
            addCriterion("state_id not in", values, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdBetween(String value1, String value2) {
            addCriterion("state_id between", value1, value2, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdNotBetween(String value1, String value2) {
            addCriterion("state_id not between", value1, value2, "stateId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdIsNull() {
            addCriterion("province_id is null");
            return (Criteria) this;
        }

        public Criteria andProvinceIdIsNotNull() {
            addCriterion("province_id is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceIdEqualTo(String value) {
            addCriterion("province_id =", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdNotEqualTo(String value) {
            addCriterion("province_id <>", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdGreaterThan(String value) {
            addCriterion("province_id >", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdGreaterThanOrEqualTo(String value) {
            addCriterion("province_id >=", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdLessThan(String value) {
            addCriterion("province_id <", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdLessThanOrEqualTo(String value) {
            addCriterion("province_id <=", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdLike(String value) {
            addCriterion("province_id like", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdNotLike(String value) {
            addCriterion("province_id not like", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdIn(List<String> values) {
            addCriterion("province_id in", values, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdNotIn(List<String> values) {
            addCriterion("province_id not in", values, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdBetween(String value1, String value2) {
            addCriterion("province_id between", value1, value2, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdNotBetween(String value1, String value2) {
            addCriterion("province_id not between", value1, value2, "provinceId");
            return (Criteria) this;
        }

        public Criteria andCityIdIsNull() {
            addCriterion("city_id is null");
            return (Criteria) this;
        }

        public Criteria andCityIdIsNotNull() {
            addCriterion("city_id is not null");
            return (Criteria) this;
        }

        public Criteria andCityIdEqualTo(String value) {
            addCriterion("city_id =", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotEqualTo(String value) {
            addCriterion("city_id <>", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdGreaterThan(String value) {
            addCriterion("city_id >", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdGreaterThanOrEqualTo(String value) {
            addCriterion("city_id >=", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLessThan(String value) {
            addCriterion("city_id <", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLessThanOrEqualTo(String value) {
            addCriterion("city_id <=", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLike(String value) {
            addCriterion("city_id like", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotLike(String value) {
            addCriterion("city_id not like", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdIn(List<String> values) {
            addCriterion("city_id in", values, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotIn(List<String> values) {
            addCriterion("city_id not in", values, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdBetween(String value1, String value2) {
            addCriterion("city_id between", value1, value2, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotBetween(String value1, String value2) {
            addCriterion("city_id not between", value1, value2, "cityId");
            return (Criteria) this;
        }

        public Criteria andTownIdIsNull() {
            addCriterion("town_id is null");
            return (Criteria) this;
        }

        public Criteria andTownIdIsNotNull() {
            addCriterion("town_id is not null");
            return (Criteria) this;
        }

        public Criteria andTownIdEqualTo(String value) {
            addCriterion("town_id =", value, "townId");
            return (Criteria) this;
        }

        public Criteria andTownIdNotEqualTo(String value) {
            addCriterion("town_id <>", value, "townId");
            return (Criteria) this;
        }

        public Criteria andTownIdGreaterThan(String value) {
            addCriterion("town_id >", value, "townId");
            return (Criteria) this;
        }

        public Criteria andTownIdGreaterThanOrEqualTo(String value) {
            addCriterion("town_id >=", value, "townId");
            return (Criteria) this;
        }

        public Criteria andTownIdLessThan(String value) {
            addCriterion("town_id <", value, "townId");
            return (Criteria) this;
        }

        public Criteria andTownIdLessThanOrEqualTo(String value) {
            addCriterion("town_id <=", value, "townId");
            return (Criteria) this;
        }

        public Criteria andTownIdLike(String value) {
            addCriterion("town_id like", value, "townId");
            return (Criteria) this;
        }

        public Criteria andTownIdNotLike(String value) {
            addCriterion("town_id not like", value, "townId");
            return (Criteria) this;
        }

        public Criteria andTownIdIn(List<String> values) {
            addCriterion("town_id in", values, "townId");
            return (Criteria) this;
        }

        public Criteria andTownIdNotIn(List<String> values) {
            addCriterion("town_id not in", values, "townId");
            return (Criteria) this;
        }

        public Criteria andTownIdBetween(String value1, String value2) {
            addCriterion("town_id between", value1, value2, "townId");
            return (Criteria) this;
        }

        public Criteria andTownIdNotBetween(String value1, String value2) {
            addCriterion("town_id not between", value1, value2, "townId");
            return (Criteria) this;
        }

        public Criteria andAddressLocationIsNull() {
            addCriterion("address_location is null");
            return (Criteria) this;
        }

        public Criteria andAddressLocationIsNotNull() {
            addCriterion("address_location is not null");
            return (Criteria) this;
        }

        public Criteria andAddressLocationEqualTo(String value) {
            addCriterion("address_location =", value, "addressLocation");
            return (Criteria) this;
        }

        public Criteria andAddressLocationNotEqualTo(String value) {
            addCriterion("address_location <>", value, "addressLocation");
            return (Criteria) this;
        }

        public Criteria andAddressLocationGreaterThan(String value) {
            addCriterion("address_location >", value, "addressLocation");
            return (Criteria) this;
        }

        public Criteria andAddressLocationGreaterThanOrEqualTo(String value) {
            addCriterion("address_location >=", value, "addressLocation");
            return (Criteria) this;
        }

        public Criteria andAddressLocationLessThan(String value) {
            addCriterion("address_location <", value, "addressLocation");
            return (Criteria) this;
        }

        public Criteria andAddressLocationLessThanOrEqualTo(String value) {
            addCriterion("address_location <=", value, "addressLocation");
            return (Criteria) this;
        }

        public Criteria andAddressLocationLike(String value) {
            addCriterion("address_location like", value, "addressLocation");
            return (Criteria) this;
        }

        public Criteria andAddressLocationNotLike(String value) {
            addCriterion("address_location not like", value, "addressLocation");
            return (Criteria) this;
        }

        public Criteria andAddressLocationIn(List<String> values) {
            addCriterion("address_location in", values, "addressLocation");
            return (Criteria) this;
        }

        public Criteria andAddressLocationNotIn(List<String> values) {
            addCriterion("address_location not in", values, "addressLocation");
            return (Criteria) this;
        }

        public Criteria andAddressLocationBetween(String value1, String value2) {
            addCriterion("address_location between", value1, value2, "addressLocation");
            return (Criteria) this;
        }

        public Criteria andAddressLocationNotBetween(String value1, String value2) {
            addCriterion("address_location not between", value1, value2, "addressLocation");
            return (Criteria) this;
        }

        public Criteria andAddressPhoneIsNull() {
            addCriterion("address_phone is null");
            return (Criteria) this;
        }

        public Criteria andAddressPhoneIsNotNull() {
            addCriterion("address_phone is not null");
            return (Criteria) this;
        }

        public Criteria andAddressPhoneEqualTo(String value) {
            addCriterion("address_phone =", value, "addressPhone");
            return (Criteria) this;
        }

        public Criteria andAddressPhoneNotEqualTo(String value) {
            addCriterion("address_phone <>", value, "addressPhone");
            return (Criteria) this;
        }

        public Criteria andAddressPhoneGreaterThan(String value) {
            addCriterion("address_phone >", value, "addressPhone");
            return (Criteria) this;
        }

        public Criteria andAddressPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("address_phone >=", value, "addressPhone");
            return (Criteria) this;
        }

        public Criteria andAddressPhoneLessThan(String value) {
            addCriterion("address_phone <", value, "addressPhone");
            return (Criteria) this;
        }

        public Criteria andAddressPhoneLessThanOrEqualTo(String value) {
            addCriterion("address_phone <=", value, "addressPhone");
            return (Criteria) this;
        }

        public Criteria andAddressPhoneLike(String value) {
            addCriterion("address_phone like", value, "addressPhone");
            return (Criteria) this;
        }

        public Criteria andAddressPhoneNotLike(String value) {
            addCriterion("address_phone not like", value, "addressPhone");
            return (Criteria) this;
        }

        public Criteria andAddressPhoneIn(List<String> values) {
            addCriterion("address_phone in", values, "addressPhone");
            return (Criteria) this;
        }

        public Criteria andAddressPhoneNotIn(List<String> values) {
            addCriterion("address_phone not in", values, "addressPhone");
            return (Criteria) this;
        }

        public Criteria andAddressPhoneBetween(String value1, String value2) {
            addCriterion("address_phone between", value1, value2, "addressPhone");
            return (Criteria) this;
        }

        public Criteria andAddressPhoneNotBetween(String value1, String value2) {
            addCriterion("address_phone not between", value1, value2, "addressPhone");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeIsNull() {
            addCriterion("address_postcode is null");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeIsNotNull() {
            addCriterion("address_postcode is not null");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeEqualTo(Integer value) {
            addCriterion("address_postcode =", value, "addressPostcode");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeNotEqualTo(Integer value) {
            addCriterion("address_postcode <>", value, "addressPostcode");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeGreaterThan(Integer value) {
            addCriterion("address_postcode >", value, "addressPostcode");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("address_postcode >=", value, "addressPostcode");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeLessThan(Integer value) {
            addCriterion("address_postcode <", value, "addressPostcode");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeLessThanOrEqualTo(Integer value) {
            addCriterion("address_postcode <=", value, "addressPostcode");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeIn(List<Integer> values) {
            addCriterion("address_postcode in", values, "addressPostcode");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeNotIn(List<Integer> values) {
            addCriterion("address_postcode not in", values, "addressPostcode");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeBetween(Integer value1, Integer value2) {
            addCriterion("address_postcode between", value1, value2, "addressPostcode");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeNotBetween(Integer value1, Integer value2) {
            addCriterion("address_postcode not between", value1, value2, "addressPostcode");
            return (Criteria) this;
        }

        public Criteria andAddressFaddrAxesIsNull() {
            addCriterion("address_faddr_axes is null");
            return (Criteria) this;
        }

        public Criteria andAddressFaddrAxesIsNotNull() {
            addCriterion("address_faddr_axes is not null");
            return (Criteria) this;
        }

        public Criteria andAddressFaddrAxesEqualTo(String value) {
            addCriterion("address_faddr_axes =", value, "addressFaddrAxes");
            return (Criteria) this;
        }

        public Criteria andAddressFaddrAxesNotEqualTo(String value) {
            addCriterion("address_faddr_axes <>", value, "addressFaddrAxes");
            return (Criteria) this;
        }

        public Criteria andAddressFaddrAxesGreaterThan(String value) {
            addCriterion("address_faddr_axes >", value, "addressFaddrAxes");
            return (Criteria) this;
        }

        public Criteria andAddressFaddrAxesGreaterThanOrEqualTo(String value) {
            addCriterion("address_faddr_axes >=", value, "addressFaddrAxes");
            return (Criteria) this;
        }

        public Criteria andAddressFaddrAxesLessThan(String value) {
            addCriterion("address_faddr_axes <", value, "addressFaddrAxes");
            return (Criteria) this;
        }

        public Criteria andAddressFaddrAxesLessThanOrEqualTo(String value) {
            addCriterion("address_faddr_axes <=", value, "addressFaddrAxes");
            return (Criteria) this;
        }

        public Criteria andAddressFaddrAxesLike(String value) {
            addCriterion("address_faddr_axes like", value, "addressFaddrAxes");
            return (Criteria) this;
        }

        public Criteria andAddressFaddrAxesNotLike(String value) {
            addCriterion("address_faddr_axes not like", value, "addressFaddrAxes");
            return (Criteria) this;
        }

        public Criteria andAddressFaddrAxesIn(List<String> values) {
            addCriterion("address_faddr_axes in", values, "addressFaddrAxes");
            return (Criteria) this;
        }

        public Criteria andAddressFaddrAxesNotIn(List<String> values) {
            addCriterion("address_faddr_axes not in", values, "addressFaddrAxes");
            return (Criteria) this;
        }

        public Criteria andAddressFaddrAxesBetween(String value1, String value2) {
            addCriterion("address_faddr_axes between", value1, value2, "addressFaddrAxes");
            return (Criteria) this;
        }

        public Criteria andAddressFaddrAxesNotBetween(String value1, String value2) {
            addCriterion("address_faddr_axes not between", value1, value2, "addressFaddrAxes");
            return (Criteria) this;
        }

        public Criteria andAddressIsDefIsNull() {
            addCriterion("address_is_def is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsDefIsNotNull() {
            addCriterion("address_is_def is not null");
            return (Criteria) this;
        }

        public Criteria andAddressIsDefEqualTo(Integer value) {
            addCriterion("address_is_def =", value, "addressIsDef");
            return (Criteria) this;
        }

        public Criteria andAddressIsDefNotEqualTo(Integer value) {
            addCriterion("address_is_def <>", value, "addressIsDef");
            return (Criteria) this;
        }

        public Criteria andAddressIsDefGreaterThan(Integer value) {
            addCriterion("address_is_def >", value, "addressIsDef");
            return (Criteria) this;
        }

        public Criteria andAddressIsDefGreaterThanOrEqualTo(Integer value) {
            addCriterion("address_is_def >=", value, "addressIsDef");
            return (Criteria) this;
        }

        public Criteria andAddressIsDefLessThan(Integer value) {
            addCriterion("address_is_def <", value, "addressIsDef");
            return (Criteria) this;
        }

        public Criteria andAddressIsDefLessThanOrEqualTo(Integer value) {
            addCriterion("address_is_def <=", value, "addressIsDef");
            return (Criteria) this;
        }

        public Criteria andAddressIsDefIn(List<Integer> values) {
            addCriterion("address_is_def in", values, "addressIsDef");
            return (Criteria) this;
        }

        public Criteria andAddressIsDefNotIn(List<Integer> values) {
            addCriterion("address_is_def not in", values, "addressIsDef");
            return (Criteria) this;
        }

        public Criteria andAddressIsDefBetween(Integer value1, Integer value2) {
            addCriterion("address_is_def between", value1, value2, "addressIsDef");
            return (Criteria) this;
        }

        public Criteria andAddressIsDefNotBetween(Integer value1, Integer value2) {
            addCriterion("address_is_def not between", value1, value2, "addressIsDef");
            return (Criteria) this;
        }

        public Criteria andAddressNameIsNull() {
            addCriterion("address_name is null");
            return (Criteria) this;
        }

        public Criteria andAddressNameIsNotNull() {
            addCriterion("address_name is not null");
            return (Criteria) this;
        }

        public Criteria andAddressNameEqualTo(String value) {
            addCriterion("address_name =", value, "addressName");
            return (Criteria) this;
        }

        public Criteria andAddressNameNotEqualTo(String value) {
            addCriterion("address_name <>", value, "addressName");
            return (Criteria) this;
        }

        public Criteria andAddressNameGreaterThan(String value) {
            addCriterion("address_name >", value, "addressName");
            return (Criteria) this;
        }

        public Criteria andAddressNameGreaterThanOrEqualTo(String value) {
            addCriterion("address_name >=", value, "addressName");
            return (Criteria) this;
        }

        public Criteria andAddressNameLessThan(String value) {
            addCriterion("address_name <", value, "addressName");
            return (Criteria) this;
        }

        public Criteria andAddressNameLessThanOrEqualTo(String value) {
            addCriterion("address_name <=", value, "addressName");
            return (Criteria) this;
        }

        public Criteria andAddressNameLike(String value) {
            addCriterion("address_name like", value, "addressName");
            return (Criteria) this;
        }

        public Criteria andAddressNameNotLike(String value) {
            addCriterion("address_name not like", value, "addressName");
            return (Criteria) this;
        }

        public Criteria andAddressNameIn(List<String> values) {
            addCriterion("address_name in", values, "addressName");
            return (Criteria) this;
        }

        public Criteria andAddressNameNotIn(List<String> values) {
            addCriterion("address_name not in", values, "addressName");
            return (Criteria) this;
        }

        public Criteria andAddressNameBetween(String value1, String value2) {
            addCriterion("address_name between", value1, value2, "addressName");
            return (Criteria) this;
        }

        public Criteria andAddressNameNotBetween(String value1, String value2) {
            addCriterion("address_name not between", value1, value2, "addressName");
            return (Criteria) this;
        }

        public Criteria andAddressRecipientsIsNull() {
            addCriterion("address_recipients is null");
            return (Criteria) this;
        }

        public Criteria andAddressRecipientsIsNotNull() {
            addCriterion("address_recipients is not null");
            return (Criteria) this;
        }

        public Criteria andAddressRecipientsEqualTo(String value) {
            addCriterion("address_recipients =", value, "addressRecipients");
            return (Criteria) this;
        }

        public Criteria andAddressRecipientsNotEqualTo(String value) {
            addCriterion("address_recipients <>", value, "addressRecipients");
            return (Criteria) this;
        }

        public Criteria andAddressRecipientsGreaterThan(String value) {
            addCriterion("address_recipients >", value, "addressRecipients");
            return (Criteria) this;
        }

        public Criteria andAddressRecipientsGreaterThanOrEqualTo(String value) {
            addCriterion("address_recipients >=", value, "addressRecipients");
            return (Criteria) this;
        }

        public Criteria andAddressRecipientsLessThan(String value) {
            addCriterion("address_recipients <", value, "addressRecipients");
            return (Criteria) this;
        }

        public Criteria andAddressRecipientsLessThanOrEqualTo(String value) {
            addCriterion("address_recipients <=", value, "addressRecipients");
            return (Criteria) this;
        }

        public Criteria andAddressRecipientsLike(String value) {
            addCriterion("address_recipients like", value, "addressRecipients");
            return (Criteria) this;
        }

        public Criteria andAddressRecipientsNotLike(String value) {
            addCriterion("address_recipients not like", value, "addressRecipients");
            return (Criteria) this;
        }

        public Criteria andAddressRecipientsIn(List<String> values) {
            addCriterion("address_recipients in", values, "addressRecipients");
            return (Criteria) this;
        }

        public Criteria andAddressRecipientsNotIn(List<String> values) {
            addCriterion("address_recipients not in", values, "addressRecipients");
            return (Criteria) this;
        }

        public Criteria andAddressRecipientsBetween(String value1, String value2) {
            addCriterion("address_recipients between", value1, value2, "addressRecipients");
            return (Criteria) this;
        }

        public Criteria andAddressRecipientsNotBetween(String value1, String value2) {
            addCriterion("address_recipients not between", value1, value2, "addressRecipients");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table eshop_address
     *
     * @mbg.generated do_not_delete_during_merge Thu May 17 16:36:46 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table eshop_address
     *
     * @mbg.generated Thu May 17 16:36:46 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}