package online.shixun.demo.eshop.dto;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EshopOrder implements Serializable {
    private List<EshopOrderItem> items = new ArrayList<>();

    public List<EshopOrderItem> getItems() {
        return items;
    }

    public void setItems(List<EshopOrderItem> items) {
        this.items = items;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_order.id
     *
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_order.is_del
     *
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    private Integer isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_order.create_time
     *
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_order.update_time
     *
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_order.user_id
     *
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_order.address_id
     *
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    private String addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_order.order_deliver_fee
     *
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    private Float orderDeliverFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_order.order_total_fee
     *
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    private Float orderTotalFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_order.order_price
     *
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    private Float orderPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_order.order_payment_way
     *
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    private Integer orderPaymentWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_order.order_payment_cash
     *
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    private Integer orderPaymentCash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_order.order_is_paiy
     *
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    private Integer orderIsPaiy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_order.order_state
     *
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    private Integer orderState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_order.order_recipients
     *
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    private String orderRecipients;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eshop_order
     *
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_order.id
     *
     * @return the value of eshop_order.id
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_order.id
     *
     * @param id the value for eshop_order.id
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_order.is_del
     *
     * @return the value of eshop_order.is_del
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_order.is_del
     *
     * @param isDel the value for eshop_order.is_del
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_order.create_time
     *
     * @return the value of eshop_order.create_time
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_order.create_time
     *
     * @param createTime the value for eshop_order.create_time
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_order.update_time
     *
     * @return the value of eshop_order.update_time
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_order.update_time
     *
     * @param updateTime the value for eshop_order.update_time
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_order.user_id
     *
     * @return the value of eshop_order.user_id
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_order.user_id
     *
     * @param userId the value for eshop_order.user_id
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_order.address_id
     *
     * @return the value of eshop_order.address_id
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    public String getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_order.address_id
     *
     * @param addressId the value for eshop_order.address_id
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    public void setAddressId(String addressId) {
        this.addressId = addressId == null ? null : addressId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_order.order_deliver_fee
     *
     * @return the value of eshop_order.order_deliver_fee
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    public Float getOrderDeliverFee() {
        return orderDeliverFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_order.order_deliver_fee
     *
     * @param orderDeliverFee the value for eshop_order.order_deliver_fee
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    public void setOrderDeliverFee(Float orderDeliverFee) {
        this.orderDeliverFee = orderDeliverFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_order.order_total_fee
     *
     * @return the value of eshop_order.order_total_fee
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    public Float getOrderTotalFee() {
        return orderTotalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_order.order_total_fee
     *
     * @param orderTotalFee the value for eshop_order.order_total_fee
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    public void setOrderTotalFee(Float orderTotalFee) {
        this.orderTotalFee = orderTotalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_order.order_price
     *
     * @return the value of eshop_order.order_price
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    public Float getOrderPrice() {
        return orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_order.order_price
     *
     * @param orderPrice the value for eshop_order.order_price
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    public void setOrderPrice(Float orderPrice) {
        this.orderPrice = orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_order.order_payment_way
     *
     * @return the value of eshop_order.order_payment_way
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    public Integer getOrderPaymentWay() {
        return orderPaymentWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_order.order_payment_way
     *
     * @param orderPaymentWay the value for eshop_order.order_payment_way
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    public void setOrderPaymentWay(Integer orderPaymentWay) {
        this.orderPaymentWay = orderPaymentWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_order.order_payment_cash
     *
     * @return the value of eshop_order.order_payment_cash
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    public Integer getOrderPaymentCash() {
        return orderPaymentCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_order.order_payment_cash
     *
     * @param orderPaymentCash the value for eshop_order.order_payment_cash
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    public void setOrderPaymentCash(Integer orderPaymentCash) {
        this.orderPaymentCash = orderPaymentCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_order.order_is_paiy
     *
     * @return the value of eshop_order.order_is_paiy
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    public Integer getOrderIsPaiy() {
        return orderIsPaiy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_order.order_is_paiy
     *
     * @param orderIsPaiy the value for eshop_order.order_is_paiy
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    public void setOrderIsPaiy(Integer orderIsPaiy) {
        this.orderIsPaiy = orderIsPaiy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_order.order_state
     *
     * @return the value of eshop_order.order_state
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    public Integer getOrderState() {
        return orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_order.order_state
     *
     * @param orderState the value for eshop_order.order_state
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    public void setOrderState(Integer orderState) {
        this.orderState = orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_order.order_recipients
     *
     * @return the value of eshop_order.order_recipients
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    public String getOrderRecipients() {
        return orderRecipients;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_order.order_recipients
     *
     * @param orderRecipients the value for eshop_order.order_recipients
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    public void setOrderRecipients(String orderRecipients) {
        this.orderRecipients = orderRecipients == null ? null : orderRecipients.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_order
     *
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", isDel=").append(isDel);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", userId=").append(userId);
        sb.append(", addressId=").append(addressId);
        sb.append(", orderDeliverFee=").append(orderDeliverFee);
        sb.append(", orderTotalFee=").append(orderTotalFee);
        sb.append(", orderPrice=").append(orderPrice);
        sb.append(", orderPaymentWay=").append(orderPaymentWay);
        sb.append(", orderPaymentCash=").append(orderPaymentCash);
        sb.append(", orderIsPaiy=").append(orderIsPaiy);
        sb.append(", orderState=").append(orderState);
        sb.append(", orderRecipients=").append(orderRecipients);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}