package online.shixun.demo.eshop.dto;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class EshopOrderItemCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eshop_order_item
     *
     * @mbg.generated Wed May 23 10:27:25 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eshop_order_item
     *
     * @mbg.generated Wed May 23 10:27:25 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eshop_order_item
     *
     * @mbg.generated Wed May 23 10:27:25 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_order_item
     *
     * @mbg.generated Wed May 23 10:27:25 CST 2018
     */
    public EshopOrderItemCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_order_item
     *
     * @mbg.generated Wed May 23 10:27:25 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_order_item
     *
     * @mbg.generated Wed May 23 10:27:25 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_order_item
     *
     * @mbg.generated Wed May 23 10:27:25 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_order_item
     *
     * @mbg.generated Wed May 23 10:27:25 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_order_item
     *
     * @mbg.generated Wed May 23 10:27:25 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_order_item
     *
     * @mbg.generated Wed May 23 10:27:25 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_order_item
     *
     * @mbg.generated Wed May 23 10:27:25 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_order_item
     *
     * @mbg.generated Wed May 23 10:27:25 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_order_item
     *
     * @mbg.generated Wed May 23 10:27:25 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_order_item
     *
     * @mbg.generated Wed May 23 10:27:25 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table eshop_order_item
     *
     * @mbg.generated Wed May 23 10:27:25 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNull() {
            addCriterion("is_del is null");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNotNull() {
            addCriterion("is_del is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelEqualTo(Integer value) {
            addCriterion("is_del =", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotEqualTo(Integer value) {
            addCriterion("is_del <>", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThan(Integer value) {
            addCriterion("is_del >", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_del >=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThan(Integer value) {
            addCriterion("is_del <", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThanOrEqualTo(Integer value) {
            addCriterion("is_del <=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelIn(List<Integer> values) {
            addCriterion("is_del in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotIn(List<Integer> values) {
            addCriterion("is_del not in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelBetween(Integer value1, Integer value2) {
            addCriterion("is_del between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotBetween(Integer value1, Integer value2) {
            addCriterion("is_del not between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterionForJDBCDate("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterionForJDBCDate("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterionForJDBCDate("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterionForJDBCDate("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterionForJDBCDate("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterionForJDBCDate("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("order_id like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("order_id not like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<String> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<String> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andColorIdIsNull() {
            addCriterion("color_id is null");
            return (Criteria) this;
        }

        public Criteria andColorIdIsNotNull() {
            addCriterion("color_id is not null");
            return (Criteria) this;
        }

        public Criteria andColorIdEqualTo(String value) {
            addCriterion("color_id =", value, "colorId");
            return (Criteria) this;
        }

        public Criteria andColorIdNotEqualTo(String value) {
            addCriterion("color_id <>", value, "colorId");
            return (Criteria) this;
        }

        public Criteria andColorIdGreaterThan(String value) {
            addCriterion("color_id >", value, "colorId");
            return (Criteria) this;
        }

        public Criteria andColorIdGreaterThanOrEqualTo(String value) {
            addCriterion("color_id >=", value, "colorId");
            return (Criteria) this;
        }

        public Criteria andColorIdLessThan(String value) {
            addCriterion("color_id <", value, "colorId");
            return (Criteria) this;
        }

        public Criteria andColorIdLessThanOrEqualTo(String value) {
            addCriterion("color_id <=", value, "colorId");
            return (Criteria) this;
        }

        public Criteria andColorIdLike(String value) {
            addCriterion("color_id like", value, "colorId");
            return (Criteria) this;
        }

        public Criteria andColorIdNotLike(String value) {
            addCriterion("color_id not like", value, "colorId");
            return (Criteria) this;
        }

        public Criteria andColorIdIn(List<String> values) {
            addCriterion("color_id in", values, "colorId");
            return (Criteria) this;
        }

        public Criteria andColorIdNotIn(List<String> values) {
            addCriterion("color_id not in", values, "colorId");
            return (Criteria) this;
        }

        public Criteria andColorIdBetween(String value1, String value2) {
            addCriterion("color_id between", value1, value2, "colorId");
            return (Criteria) this;
        }

        public Criteria andColorIdNotBetween(String value1, String value2) {
            addCriterion("color_id not between", value1, value2, "colorId");
            return (Criteria) this;
        }

        public Criteria andSizeIdIsNull() {
            addCriterion("size_id is null");
            return (Criteria) this;
        }

        public Criteria andSizeIdIsNotNull() {
            addCriterion("size_id is not null");
            return (Criteria) this;
        }

        public Criteria andSizeIdEqualTo(String value) {
            addCriterion("size_id =", value, "sizeId");
            return (Criteria) this;
        }

        public Criteria andSizeIdNotEqualTo(String value) {
            addCriterion("size_id <>", value, "sizeId");
            return (Criteria) this;
        }

        public Criteria andSizeIdGreaterThan(String value) {
            addCriterion("size_id >", value, "sizeId");
            return (Criteria) this;
        }

        public Criteria andSizeIdGreaterThanOrEqualTo(String value) {
            addCriterion("size_id >=", value, "sizeId");
            return (Criteria) this;
        }

        public Criteria andSizeIdLessThan(String value) {
            addCriterion("size_id <", value, "sizeId");
            return (Criteria) this;
        }

        public Criteria andSizeIdLessThanOrEqualTo(String value) {
            addCriterion("size_id <=", value, "sizeId");
            return (Criteria) this;
        }

        public Criteria andSizeIdLike(String value) {
            addCriterion("size_id like", value, "sizeId");
            return (Criteria) this;
        }

        public Criteria andSizeIdNotLike(String value) {
            addCriterion("size_id not like", value, "sizeId");
            return (Criteria) this;
        }

        public Criteria andSizeIdIn(List<String> values) {
            addCriterion("size_id in", values, "sizeId");
            return (Criteria) this;
        }

        public Criteria andSizeIdNotIn(List<String> values) {
            addCriterion("size_id not in", values, "sizeId");
            return (Criteria) this;
        }

        public Criteria andSizeIdBetween(String value1, String value2) {
            addCriterion("size_id between", value1, value2, "sizeId");
            return (Criteria) this;
        }

        public Criteria andSizeIdNotBetween(String value1, String value2) {
            addCriterion("size_id not between", value1, value2, "sizeId");
            return (Criteria) this;
        }

        public Criteria andOrderItemNameIsNull() {
            addCriterion("order_item_name is null");
            return (Criteria) this;
        }

        public Criteria andOrderItemNameIsNotNull() {
            addCriterion("order_item_name is not null");
            return (Criteria) this;
        }

        public Criteria andOrderItemNameEqualTo(String value) {
            addCriterion("order_item_name =", value, "orderItemName");
            return (Criteria) this;
        }

        public Criteria andOrderItemNameNotEqualTo(String value) {
            addCriterion("order_item_name <>", value, "orderItemName");
            return (Criteria) this;
        }

        public Criteria andOrderItemNameGreaterThan(String value) {
            addCriterion("order_item_name >", value, "orderItemName");
            return (Criteria) this;
        }

        public Criteria andOrderItemNameGreaterThanOrEqualTo(String value) {
            addCriterion("order_item_name >=", value, "orderItemName");
            return (Criteria) this;
        }

        public Criteria andOrderItemNameLessThan(String value) {
            addCriterion("order_item_name <", value, "orderItemName");
            return (Criteria) this;
        }

        public Criteria andOrderItemNameLessThanOrEqualTo(String value) {
            addCriterion("order_item_name <=", value, "orderItemName");
            return (Criteria) this;
        }

        public Criteria andOrderItemNameLike(String value) {
            addCriterion("order_item_name like", value, "orderItemName");
            return (Criteria) this;
        }

        public Criteria andOrderItemNameNotLike(String value) {
            addCriterion("order_item_name not like", value, "orderItemName");
            return (Criteria) this;
        }

        public Criteria andOrderItemNameIn(List<String> values) {
            addCriterion("order_item_name in", values, "orderItemName");
            return (Criteria) this;
        }

        public Criteria andOrderItemNameNotIn(List<String> values) {
            addCriterion("order_item_name not in", values, "orderItemName");
            return (Criteria) this;
        }

        public Criteria andOrderItemNameBetween(String value1, String value2) {
            addCriterion("order_item_name between", value1, value2, "orderItemName");
            return (Criteria) this;
        }

        public Criteria andOrderItemNameNotBetween(String value1, String value2) {
            addCriterion("order_item_name not between", value1, value2, "orderItemName");
            return (Criteria) this;
        }

        public Criteria andOrderItemProiceIsNull() {
            addCriterion("order_item_proice is null");
            return (Criteria) this;
        }

        public Criteria andOrderItemProiceIsNotNull() {
            addCriterion("order_item_proice is not null");
            return (Criteria) this;
        }

        public Criteria andOrderItemProiceEqualTo(BigDecimal value) {
            addCriterion("order_item_proice =", value, "orderItemProice");
            return (Criteria) this;
        }

        public Criteria andOrderItemProiceNotEqualTo(BigDecimal value) {
            addCriterion("order_item_proice <>", value, "orderItemProice");
            return (Criteria) this;
        }

        public Criteria andOrderItemProiceGreaterThan(BigDecimal value) {
            addCriterion("order_item_proice >", value, "orderItemProice");
            return (Criteria) this;
        }

        public Criteria andOrderItemProiceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("order_item_proice >=", value, "orderItemProice");
            return (Criteria) this;
        }

        public Criteria andOrderItemProiceLessThan(BigDecimal value) {
            addCriterion("order_item_proice <", value, "orderItemProice");
            return (Criteria) this;
        }

        public Criteria andOrderItemProiceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("order_item_proice <=", value, "orderItemProice");
            return (Criteria) this;
        }

        public Criteria andOrderItemProiceIn(List<BigDecimal> values) {
            addCriterion("order_item_proice in", values, "orderItemProice");
            return (Criteria) this;
        }

        public Criteria andOrderItemProiceNotIn(List<BigDecimal> values) {
            addCriterion("order_item_proice not in", values, "orderItemProice");
            return (Criteria) this;
        }

        public Criteria andOrderItemProiceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("order_item_proice between", value1, value2, "orderItemProice");
            return (Criteria) this;
        }

        public Criteria andOrderItemProiceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("order_item_proice not between", value1, value2, "orderItemProice");
            return (Criteria) this;
        }

        public Criteria andOrderItemAmountIsNull() {
            addCriterion("order_item_amount is null");
            return (Criteria) this;
        }

        public Criteria andOrderItemAmountIsNotNull() {
            addCriterion("order_item_amount is not null");
            return (Criteria) this;
        }

        public Criteria andOrderItemAmountEqualTo(Integer value) {
            addCriterion("order_item_amount =", value, "orderItemAmount");
            return (Criteria) this;
        }

        public Criteria andOrderItemAmountNotEqualTo(Integer value) {
            addCriterion("order_item_amount <>", value, "orderItemAmount");
            return (Criteria) this;
        }

        public Criteria andOrderItemAmountGreaterThan(Integer value) {
            addCriterion("order_item_amount >", value, "orderItemAmount");
            return (Criteria) this;
        }

        public Criteria andOrderItemAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_item_amount >=", value, "orderItemAmount");
            return (Criteria) this;
        }

        public Criteria andOrderItemAmountLessThan(Integer value) {
            addCriterion("order_item_amount <", value, "orderItemAmount");
            return (Criteria) this;
        }

        public Criteria andOrderItemAmountLessThanOrEqualTo(Integer value) {
            addCriterion("order_item_amount <=", value, "orderItemAmount");
            return (Criteria) this;
        }

        public Criteria andOrderItemAmountIn(List<Integer> values) {
            addCriterion("order_item_amount in", values, "orderItemAmount");
            return (Criteria) this;
        }

        public Criteria andOrderItemAmountNotIn(List<Integer> values) {
            addCriterion("order_item_amount not in", values, "orderItemAmount");
            return (Criteria) this;
        }

        public Criteria andOrderItemAmountBetween(Integer value1, Integer value2) {
            addCriterion("order_item_amount between", value1, value2, "orderItemAmount");
            return (Criteria) this;
        }

        public Criteria andOrderItemAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("order_item_amount not between", value1, value2, "orderItemAmount");
            return (Criteria) this;
        }

        public Criteria andOrderItemUrlIsNull() {
            addCriterion("order_item_url is null");
            return (Criteria) this;
        }

        public Criteria andOrderItemUrlIsNotNull() {
            addCriterion("order_item_url is not null");
            return (Criteria) this;
        }

        public Criteria andOrderItemUrlEqualTo(String value) {
            addCriterion("order_item_url =", value, "orderItemUrl");
            return (Criteria) this;
        }

        public Criteria andOrderItemUrlNotEqualTo(String value) {
            addCriterion("order_item_url <>", value, "orderItemUrl");
            return (Criteria) this;
        }

        public Criteria andOrderItemUrlGreaterThan(String value) {
            addCriterion("order_item_url >", value, "orderItemUrl");
            return (Criteria) this;
        }

        public Criteria andOrderItemUrlGreaterThanOrEqualTo(String value) {
            addCriterion("order_item_url >=", value, "orderItemUrl");
            return (Criteria) this;
        }

        public Criteria andOrderItemUrlLessThan(String value) {
            addCriterion("order_item_url <", value, "orderItemUrl");
            return (Criteria) this;
        }

        public Criteria andOrderItemUrlLessThanOrEqualTo(String value) {
            addCriterion("order_item_url <=", value, "orderItemUrl");
            return (Criteria) this;
        }

        public Criteria andOrderItemUrlLike(String value) {
            addCriterion("order_item_url like", value, "orderItemUrl");
            return (Criteria) this;
        }

        public Criteria andOrderItemUrlNotLike(String value) {
            addCriterion("order_item_url not like", value, "orderItemUrl");
            return (Criteria) this;
        }

        public Criteria andOrderItemUrlIn(List<String> values) {
            addCriterion("order_item_url in", values, "orderItemUrl");
            return (Criteria) this;
        }

        public Criteria andOrderItemUrlNotIn(List<String> values) {
            addCriterion("order_item_url not in", values, "orderItemUrl");
            return (Criteria) this;
        }

        public Criteria andOrderItemUrlBetween(String value1, String value2) {
            addCriterion("order_item_url between", value1, value2, "orderItemUrl");
            return (Criteria) this;
        }

        public Criteria andOrderItemUrlNotBetween(String value1, String value2) {
            addCriterion("order_item_url not between", value1, value2, "orderItemUrl");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNull() {
            addCriterion("product_id is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("product_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(String value) {
            addCriterion("product_id =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(String value) {
            addCriterion("product_id <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(String value) {
            addCriterion("product_id >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(String value) {
            addCriterion("product_id >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(String value) {
            addCriterion("product_id <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(String value) {
            addCriterion("product_id <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLike(String value) {
            addCriterion("product_id like", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotLike(String value) {
            addCriterion("product_id not like", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<String> values) {
            addCriterion("product_id in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<String> values) {
            addCriterion("product_id not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(String value1, String value2) {
            addCriterion("product_id between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(String value1, String value2) {
            addCriterion("product_id not between", value1, value2, "productId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table eshop_order_item
     *
     * @mbg.generated do_not_delete_during_merge Wed May 23 10:27:25 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table eshop_order_item
     *
     * @mbg.generated Wed May 23 10:27:25 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}