package online.shixun.demo.eshop.dto;

import java.io.Serializable;
import java.util.Date;

public class EshopActivity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_activity.id
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_activity.is_del
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    private Integer isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_activity.create_time
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_activity.update_time
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_activity.activity_name
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    private String activityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_activity.activity_content
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    private String activityContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_activity.activity_start_time
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    private Date activityStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_activity.activity_end_time
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    private Date activityEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_activity.activity_index
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    private Integer activityIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eshop_activity
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_activity.id
     *
     * @return the value of eshop_activity.id
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_activity.id
     *
     * @param id the value for eshop_activity.id
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_activity.is_del
     *
     * @return the value of eshop_activity.is_del
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_activity.is_del
     *
     * @param isDel the value for eshop_activity.is_del
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_activity.create_time
     *
     * @return the value of eshop_activity.create_time
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_activity.create_time
     *
     * @param createTime the value for eshop_activity.create_time
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_activity.update_time
     *
     * @return the value of eshop_activity.update_time
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_activity.update_time
     *
     * @param updateTime the value for eshop_activity.update_time
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_activity.activity_name
     *
     * @return the value of eshop_activity.activity_name
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_activity.activity_name
     *
     * @param activityName the value for eshop_activity.activity_name
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName == null ? null : activityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_activity.activity_content
     *
     * @return the value of eshop_activity.activity_content
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    public String getActivityContent() {
        return activityContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_activity.activity_content
     *
     * @param activityContent the value for eshop_activity.activity_content
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    public void setActivityContent(String activityContent) {
        this.activityContent = activityContent == null ? null : activityContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_activity.activity_start_time
     *
     * @return the value of eshop_activity.activity_start_time
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    public Date getActivityStartTime() {
        return activityStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_activity.activity_start_time
     *
     * @param activityStartTime the value for eshop_activity.activity_start_time
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    public void setActivityStartTime(Date activityStartTime) {
        this.activityStartTime = activityStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_activity.activity_end_time
     *
     * @return the value of eshop_activity.activity_end_time
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    public Date getActivityEndTime() {
        return activityEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_activity.activity_end_time
     *
     * @param activityEndTime the value for eshop_activity.activity_end_time
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    public void setActivityEndTime(Date activityEndTime) {
        this.activityEndTime = activityEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_activity.activity_index
     *
     * @return the value of eshop_activity.activity_index
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    public Integer getActivityIndex() {
        return activityIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_activity.activity_index
     *
     * @param activityIndex the value for eshop_activity.activity_index
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    public void setActivityIndex(Integer activityIndex) {
        this.activityIndex = activityIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_activity
     *
     * @mbg.generated Fri May 11 10:30:21 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", isDel=").append(isDel);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", activityName=").append(activityName);
        sb.append(", activityContent=").append(activityContent);
        sb.append(", activityStartTime=").append(activityStartTime);
        sb.append(", activityEndTime=").append(activityEndTime);
        sb.append(", activityIndex=").append(activityIndex);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}