package online.shixun.demo.eshop.module.contact.mapper;

import java.util.List;
import online.shixun.demo.eshop.dto.EshopContact;
import online.shixun.demo.eshop.dto.EshopContactCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface EshopContactMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_contact
     *
     * @mbg.generated Fri May 11 10:30:55 CST 2018
     */
    @SelectProvider(type=EshopContactSqlProvider.class, method="countByExample")
    long countByExample(EshopContactCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_contact
     *
     * @mbg.generated Fri May 11 10:30:55 CST 2018
     */
    @DeleteProvider(type=EshopContactSqlProvider.class, method="deleteByExample")
    int deleteByExample(EshopContactCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_contact
     *
     * @mbg.generated Fri May 11 10:30:55 CST 2018
     */
    @Delete({
        "delete from eshop_contact",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_contact
     *
     * @mbg.generated Fri May 11 10:30:55 CST 2018
     */
    @Insert({
        "insert into eshop_contact (id, is_del, ",
        "create_time, update_time, ",
        "user_id, contact_content, ",
        "contact_email, contact_message)",
        "values (#{id,jdbcType=VARCHAR}, #{isDel,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=DATE}, #{updateTime,jdbcType=DATE}, ",
        "#{userId,jdbcType=VARCHAR}, #{contactContent,jdbcType=INTEGER}, ",
        "#{contactEmail,jdbcType=VARCHAR}, #{contactMessage,jdbcType=VARCHAR})"
    })
    int insert(EshopContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_contact
     *
     * @mbg.generated Fri May 11 10:30:55 CST 2018
     */
    @InsertProvider(type=EshopContactSqlProvider.class, method="insertSelective")
    int insertSelective(EshopContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_contact
     *
     * @mbg.generated Fri May 11 10:30:55 CST 2018
     */
    @SelectProvider(type=EshopContactSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="is_del", property="isDel", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="contact_content", property="contactContent", jdbcType=JdbcType.INTEGER),
        @Result(column="contact_email", property="contactEmail", jdbcType=JdbcType.VARCHAR),
        @Result(column="contact_message", property="contactMessage", jdbcType=JdbcType.VARCHAR)
    })
    List<EshopContact> selectByExample(EshopContactCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_contact
     *
     * @mbg.generated Fri May 11 10:30:55 CST 2018
     */
    @Select({
        "select",
        "id, is_del, create_time, update_time, user_id, contact_content, contact_email, ",
        "contact_message",
        "from eshop_contact",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="is_del", property="isDel", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="contact_content", property="contactContent", jdbcType=JdbcType.INTEGER),
        @Result(column="contact_email", property="contactEmail", jdbcType=JdbcType.VARCHAR),
        @Result(column="contact_message", property="contactMessage", jdbcType=JdbcType.VARCHAR)
    })
    EshopContact selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_contact
     *
     * @mbg.generated Fri May 11 10:30:55 CST 2018
     */
    @UpdateProvider(type=EshopContactSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") EshopContact record, @Param("example") EshopContactCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_contact
     *
     * @mbg.generated Fri May 11 10:30:55 CST 2018
     */
    @UpdateProvider(type=EshopContactSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") EshopContact record, @Param("example") EshopContactCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_contact
     *
     * @mbg.generated Fri May 11 10:30:55 CST 2018
     */
    @UpdateProvider(type=EshopContactSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(EshopContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_contact
     *
     * @mbg.generated Fri May 11 10:30:55 CST 2018
     */
    @Update({
        "update eshop_contact",
        "set is_del = #{isDel,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=DATE},",
          "update_time = #{updateTime,jdbcType=DATE},",
          "user_id = #{userId,jdbcType=VARCHAR},",
          "contact_content = #{contactContent,jdbcType=INTEGER},",
          "contact_email = #{contactEmail,jdbcType=VARCHAR},",
          "contact_message = #{contactMessage,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(EshopContact record);
}