package online.shixun.demo.eshop.module.brand.mapper;

import java.util.List;
import online.shixun.demo.eshop.dto.EshopBrand;
import online.shixun.demo.eshop.dto.EshopBrandCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface EshopBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_brand
     *
     * @mbg.generated Fri May 11 10:31:39 CST 2018
     */
    @SelectProvider(type=EshopBrandSqlProvider.class, method="countByExample")
    long countByExample(EshopBrandCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_brand
     *
     * @mbg.generated Fri May 11 10:31:39 CST 2018
     */
    @DeleteProvider(type=EshopBrandSqlProvider.class, method="deleteByExample")
    int deleteByExample(EshopBrandCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_brand
     *
     * @mbg.generated Fri May 11 10:31:39 CST 2018
     */
    @Delete({
        "delete from eshop_brand",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_brand
     *
     * @mbg.generated Fri May 11 10:31:39 CST 2018
     */
    @Insert({
        "insert into eshop_brand (id, is_del, ",
        "update_time, create_time, ",
        "brand_name, brand_description, ",
        "brand_logo)",
        "values (#{id,jdbcType=VARCHAR}, #{isDel,jdbcType=INTEGER}, ",
        "#{updateTime,jdbcType=DATE}, #{createTime,jdbcType=DATE}, ",
        "#{brandName,jdbcType=VARCHAR}, #{brandDescription,jdbcType=VARCHAR}, ",
        "#{brandLogo,jdbcType=VARCHAR})"
    })
    int insert(EshopBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_brand
     *
     * @mbg.generated Fri May 11 10:31:39 CST 2018
     */
    @InsertProvider(type=EshopBrandSqlProvider.class, method="insertSelective")
    int insertSelective(EshopBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_brand
     *
     * @mbg.generated Fri May 11 10:31:39 CST 2018
     */
    @SelectProvider(type=EshopBrandSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="is_del", property="isDel", jdbcType=JdbcType.INTEGER),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="brand_name", property="brandName", jdbcType=JdbcType.VARCHAR),
        @Result(column="brand_description", property="brandDescription", jdbcType=JdbcType.VARCHAR),
        @Result(column="brand_logo", property="brandLogo", jdbcType=JdbcType.VARCHAR)
    })
    List<EshopBrand> selectByExample(EshopBrandCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_brand
     *
     * @mbg.generated Fri May 11 10:31:39 CST 2018
     */
    @Select({
        "select",
        "id, is_del, update_time, create_time, brand_name, brand_description, brand_logo",
        "from eshop_brand",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="is_del", property="isDel", jdbcType=JdbcType.INTEGER),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="brand_name", property="brandName", jdbcType=JdbcType.VARCHAR),
        @Result(column="brand_description", property="brandDescription", jdbcType=JdbcType.VARCHAR),
        @Result(column="brand_logo", property="brandLogo", jdbcType=JdbcType.VARCHAR)
    })
    EshopBrand selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_brand
     *
     * @mbg.generated Fri May 11 10:31:39 CST 2018
     */
    @UpdateProvider(type=EshopBrandSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") EshopBrand record, @Param("example") EshopBrandCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_brand
     *
     * @mbg.generated Fri May 11 10:31:39 CST 2018
     */
    @UpdateProvider(type=EshopBrandSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") EshopBrand record, @Param("example") EshopBrandCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_brand
     *
     * @mbg.generated Fri May 11 10:31:39 CST 2018
     */
    @UpdateProvider(type=EshopBrandSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(EshopBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_brand
     *
     * @mbg.generated Fri May 11 10:31:39 CST 2018
     */
    @Update({
        "update eshop_brand",
        "set is_del = #{isDel,jdbcType=INTEGER},",
          "update_time = #{updateTime,jdbcType=DATE},",
          "create_time = #{createTime,jdbcType=DATE},",
          "brand_name = #{brandName,jdbcType=VARCHAR},",
          "brand_description = #{brandDescription,jdbcType=VARCHAR},",
          "brand_logo = #{brandLogo,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(EshopBrand record);
}