package online.shixun.demo.eshop.module.comment.mapper;

import java.util.List;

import online.shixun.demo.eshop.dto.EshopComment;
import online.shixun.demo.eshop.dto.EshopCommentCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.mapping.FetchType;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface EshopCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_comment
     *
     * @mbg.generated Fri May 11 10:31:09 CST 2018
     */
    @SelectProvider(type = EshopCommentSqlProvider.class, method = "countByExample")
    long countByExample(EshopCommentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_comment
     *
     * @mbg.generated Fri May 11 10:31:09 CST 2018
     */
    @DeleteProvider(type = EshopCommentSqlProvider.class, method = "deleteByExample")
    int deleteByExample(EshopCommentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_comment
     *
     * @mbg.generated Fri May 11 10:31:09 CST 2018
     */
    @Delete({
            "delete from eshop_comment",
            "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_comment
     *
     * @mbg.generated Fri May 11 10:31:09 CST 2018
     */
    @Insert({
            "insert into eshop_comment (id, is_del, ",
            "create_time, update_time, ",
            "user_id, product_id, ",
            "common_rank, common_content)",
            "values (#{id,jdbcType=VARCHAR}, #{isDel,jdbcType=INTEGER}, ",
            "#{createTime,jdbcType=DATE}, #{updateTime,jdbcType=DATE}, ",
            "#{userId,jdbcType=VARCHAR}, #{productId,jdbcType=VARCHAR}, ",
            "#{commonRank,jdbcType=REAL}, #{commonContent,jdbcType=VARCHAR})"
    })
    int insert(EshopComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_comment
     *
     * @mbg.generated Fri May 11 10:31:09 CST 2018
     */
    @InsertProvider(type = EshopCommentSqlProvider.class, method = "insertSelective")
    int insertSelective(EshopComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_comment
     *
     * @mbg.generated Fri May 11 10:31:09 CST 2018
     */
    @SelectProvider(type = EshopCommentSqlProvider.class, method = "selectByExample")
    @Results({
            @Result(column = "id", property = "id", jdbcType = JdbcType.VARCHAR, id = true),
            @Result(column = "is_del", property = "isDel", jdbcType = JdbcType.INTEGER),
            @Result(column = "create_time", property = "createTime", jdbcType = JdbcType.DATE),
            @Result(column = "update_time", property = "updateTime", jdbcType = JdbcType.DATE),
            @Result(column = "product_id", property = "productId", jdbcType = JdbcType.VARCHAR),
            @Result(column = "common_rank", property = "commonRank", jdbcType = JdbcType.REAL),
            @Result(column = "common_content", property = "commonContent", jdbcType = JdbcType.VARCHAR),
            @Result(column = "user_id", property = "user", one = @One(
                    select = "online.shixun.demo.eshop.module.user.mapper.EshopUserMapper.selectByPrimaryKey",
                    fetchType = FetchType.EAGER
            ))
    })
    List<EshopComment> selectByExample(EshopCommentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_comment
     *
     * @mbg.generated Fri May 11 10:31:09 CST 2018
     */
    @Select({
            "select",
            "id, is_del, create_time, update_time, user_id, product_id, common_rank, common_content",
            "from eshop_comment",
            "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
            @Result(column = "id", property = "id", jdbcType = JdbcType.VARCHAR, id = true),
            @Result(column = "is_del", property = "isDel", jdbcType = JdbcType.INTEGER),
            @Result(column = "create_time", property = "createTime", jdbcType = JdbcType.DATE),
            @Result(column = "update_time", property = "updateTime", jdbcType = JdbcType.DATE),
            @Result(column = "user_id", property = "userId", jdbcType = JdbcType.VARCHAR),
            @Result(column = "product_id", property = "productId", jdbcType = JdbcType.VARCHAR),
            @Result(column = "common_rank", property = "commonRank", jdbcType = JdbcType.REAL),
            @Result(column = "common_content", property = "commonContent", jdbcType = JdbcType.VARCHAR)
    })
    EshopComment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_comment
     *
     * @mbg.generated Fri May 11 10:31:09 CST 2018
     */
    @UpdateProvider(type = EshopCommentSqlProvider.class, method = "updateByExampleSelective")
    int updateByExampleSelective(@Param("record") EshopComment record, @Param("example") EshopCommentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_comment
     *
     * @mbg.generated Fri May 11 10:31:09 CST 2018
     */
    @UpdateProvider(type = EshopCommentSqlProvider.class, method = "updateByExample")
    int updateByExample(@Param("record") EshopComment record, @Param("example") EshopCommentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_comment
     *
     * @mbg.generated Fri May 11 10:31:09 CST 2018
     */
    @UpdateProvider(type = EshopCommentSqlProvider.class, method = "updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(EshopComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_comment
     *
     * @mbg.generated Fri May 11 10:31:09 CST 2018
     */
    @Update({
            "update eshop_comment",
            "set is_del = #{isDel,jdbcType=INTEGER},",
            "create_time = #{createTime,jdbcType=DATE},",
            "update_time = #{updateTime,jdbcType=DATE},",
            "user_id = #{userId,jdbcType=VARCHAR},",
            "product_id = #{productId,jdbcType=VARCHAR},",
            "common_rank = #{commonRank,jdbcType=REAL},",
            "common_content = #{commonContent,jdbcType=VARCHAR}",
            "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(EshopComment record);
}