package online.shixun.demo.eshop.module.order.mapper;

import java.util.List;
import java.util.Map;
import online.shixun.demo.eshop.dto.EshopOrder;
import online.shixun.demo.eshop.dto.EshopOrderCriteria.Criteria;
import online.shixun.demo.eshop.dto.EshopOrderCriteria.Criterion;
import online.shixun.demo.eshop.dto.EshopOrderCriteria;
import org.apache.ibatis.jdbc.SQL;

public class EshopOrderSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_order
     *
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    public String countByExample(EshopOrderCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("eshop_order");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_order
     *
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    public String deleteByExample(EshopOrderCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("eshop_order");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_order
     *
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    public String insertSelective(EshopOrder record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("eshop_order");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=VARCHAR}");
        }
        
        if (record.getIsDel() != null) {
            sql.VALUES("is_del", "#{isDel,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=DATE}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.VALUES("update_time", "#{updateTime,jdbcType=DATE}");
        }
        
        if (record.getUserId() != null) {
            sql.VALUES("user_id", "#{userId,jdbcType=VARCHAR}");
        }
        
        if (record.getAddressId() != null) {
            sql.VALUES("address_id", "#{addressId,jdbcType=VARCHAR}");
        }
        
        if (record.getOrderDeliverFee() != null) {
            sql.VALUES("order_deliver_fee", "#{orderDeliverFee,jdbcType=REAL}");
        }
        
        if (record.getOrderTotalFee() != null) {
            sql.VALUES("order_total_fee", "#{orderTotalFee,jdbcType=REAL}");
        }
        
        if (record.getOrderPrice() != null) {
            sql.VALUES("order_price", "#{orderPrice,jdbcType=REAL}");
        }
        
        if (record.getOrderPaymentWay() != null) {
            sql.VALUES("order_payment_way", "#{orderPaymentWay,jdbcType=INTEGER}");
        }
        
        if (record.getOrderPaymentCash() != null) {
            sql.VALUES("order_payment_cash", "#{orderPaymentCash,jdbcType=INTEGER}");
        }
        
        if (record.getOrderIsPaiy() != null) {
            sql.VALUES("order_is_paiy", "#{orderIsPaiy,jdbcType=INTEGER}");
        }
        
        if (record.getOrderState() != null) {
            sql.VALUES("order_state", "#{orderState,jdbcType=INTEGER}");
        }
        
        if (record.getOrderRecipients() != null) {
            sql.VALUES("order_recipients", "#{orderRecipients,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_order
     *
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    public String selectByExample(EshopOrderCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("is_del");
        sql.SELECT("create_time");
        sql.SELECT("update_time");
        sql.SELECT("user_id");
        sql.SELECT("address_id");
        sql.SELECT("order_deliver_fee");
        sql.SELECT("order_total_fee");
        sql.SELECT("order_price");
        sql.SELECT("order_payment_way");
        sql.SELECT("order_payment_cash");
        sql.SELECT("order_is_paiy");
        sql.SELECT("order_state");
        sql.SELECT("order_recipients");
        sql.FROM("eshop_order");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_order
     *
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        EshopOrder record = (EshopOrder) parameter.get("record");
        EshopOrderCriteria example = (EshopOrderCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("eshop_order");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        }
        
        if (record.getIsDel() != null) {
            sql.SET("is_del = #{record.isDel,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{record.createTime,jdbcType=DATE}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{record.updateTime,jdbcType=DATE}");
        }
        
        if (record.getUserId() != null) {
            sql.SET("user_id = #{record.userId,jdbcType=VARCHAR}");
        }
        
        if (record.getAddressId() != null) {
            sql.SET("address_id = #{record.addressId,jdbcType=VARCHAR}");
        }
        
        if (record.getOrderDeliverFee() != null) {
            sql.SET("order_deliver_fee = #{record.orderDeliverFee,jdbcType=REAL}");
        }
        
        if (record.getOrderTotalFee() != null) {
            sql.SET("order_total_fee = #{record.orderTotalFee,jdbcType=REAL}");
        }
        
        if (record.getOrderPrice() != null) {
            sql.SET("order_price = #{record.orderPrice,jdbcType=REAL}");
        }
        
        if (record.getOrderPaymentWay() != null) {
            sql.SET("order_payment_way = #{record.orderPaymentWay,jdbcType=INTEGER}");
        }
        
        if (record.getOrderPaymentCash() != null) {
            sql.SET("order_payment_cash = #{record.orderPaymentCash,jdbcType=INTEGER}");
        }
        
        if (record.getOrderIsPaiy() != null) {
            sql.SET("order_is_paiy = #{record.orderIsPaiy,jdbcType=INTEGER}");
        }
        
        if (record.getOrderState() != null) {
            sql.SET("order_state = #{record.orderState,jdbcType=INTEGER}");
        }
        
        if (record.getOrderRecipients() != null) {
            sql.SET("order_recipients = #{record.orderRecipients,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_order
     *
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("eshop_order");
        
        sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        sql.SET("is_del = #{record.isDel,jdbcType=INTEGER}");
        sql.SET("create_time = #{record.createTime,jdbcType=DATE}");
        sql.SET("update_time = #{record.updateTime,jdbcType=DATE}");
        sql.SET("user_id = #{record.userId,jdbcType=VARCHAR}");
        sql.SET("address_id = #{record.addressId,jdbcType=VARCHAR}");
        sql.SET("order_deliver_fee = #{record.orderDeliverFee,jdbcType=REAL}");
        sql.SET("order_total_fee = #{record.orderTotalFee,jdbcType=REAL}");
        sql.SET("order_price = #{record.orderPrice,jdbcType=REAL}");
        sql.SET("order_payment_way = #{record.orderPaymentWay,jdbcType=INTEGER}");
        sql.SET("order_payment_cash = #{record.orderPaymentCash,jdbcType=INTEGER}");
        sql.SET("order_is_paiy = #{record.orderIsPaiy,jdbcType=INTEGER}");
        sql.SET("order_state = #{record.orderState,jdbcType=INTEGER}");
        sql.SET("order_recipients = #{record.orderRecipients,jdbcType=VARCHAR}");
        
        EshopOrderCriteria example = (EshopOrderCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_order
     *
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    public String updateByPrimaryKeySelective(EshopOrder record) {
        SQL sql = new SQL();
        sql.UPDATE("eshop_order");
        
        if (record.getIsDel() != null) {
            sql.SET("is_del = #{isDel,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=DATE}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{updateTime,jdbcType=DATE}");
        }
        
        if (record.getUserId() != null) {
            sql.SET("user_id = #{userId,jdbcType=VARCHAR}");
        }
        
        if (record.getAddressId() != null) {
            sql.SET("address_id = #{addressId,jdbcType=VARCHAR}");
        }
        
        if (record.getOrderDeliverFee() != null) {
            sql.SET("order_deliver_fee = #{orderDeliverFee,jdbcType=REAL}");
        }
        
        if (record.getOrderTotalFee() != null) {
            sql.SET("order_total_fee = #{orderTotalFee,jdbcType=REAL}");
        }
        
        if (record.getOrderPrice() != null) {
            sql.SET("order_price = #{orderPrice,jdbcType=REAL}");
        }
        
        if (record.getOrderPaymentWay() != null) {
            sql.SET("order_payment_way = #{orderPaymentWay,jdbcType=INTEGER}");
        }
        
        if (record.getOrderPaymentCash() != null) {
            sql.SET("order_payment_cash = #{orderPaymentCash,jdbcType=INTEGER}");
        }
        
        if (record.getOrderIsPaiy() != null) {
            sql.SET("order_is_paiy = #{orderIsPaiy,jdbcType=INTEGER}");
        }
        
        if (record.getOrderState() != null) {
            sql.SET("order_state = #{orderState,jdbcType=INTEGER}");
        }
        
        if (record.getOrderRecipients() != null) {
            sql.SET("order_recipients = #{orderRecipients,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_order
     *
     * @mbg.generated Thu May 17 15:54:17 CST 2018
     */
    protected void applyWhere(SQL sql, EshopOrderCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}