package online.shixun.demo.eshop.module.order.mapper;

import java.util.List;
import online.shixun.demo.eshop.dto.EshopOrderItem;
import online.shixun.demo.eshop.dto.EshopOrderItemCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface EshopOrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_order_item
     *
     * @mbg.generated Wed May 23 10:27:25 CST 2018
     */
    @SelectProvider(type=EshopOrderItemSqlProvider.class, method="countByExample")
    long countByExample(EshopOrderItemCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_order_item
     *
     * @mbg.generated Wed May 23 10:27:25 CST 2018
     */
    @DeleteProvider(type=EshopOrderItemSqlProvider.class, method="deleteByExample")
    int deleteByExample(EshopOrderItemCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_order_item
     *
     * @mbg.generated Wed May 23 10:27:25 CST 2018
     */
    @Delete({
        "delete from eshop_order_item",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_order_item
     *
     * @mbg.generated Wed May 23 10:27:25 CST 2018
     */
    @Insert({
        "insert into eshop_order_item (id, is_del, ",
        "update_time, create_time, ",
        "order_id, color_id, ",
        "size_id, order_item_name, ",
        "order_item_proice, order_item_amount, ",
        "order_item_url, product_id)",
        "values (#{id,jdbcType=VARCHAR}, #{isDel,jdbcType=INTEGER}, ",
        "#{updateTime,jdbcType=DATE}, #{createTime,jdbcType=DATE}, ",
        "#{orderId,jdbcType=VARCHAR}, #{colorId,jdbcType=VARCHAR}, ",
        "#{sizeId,jdbcType=VARCHAR}, #{orderItemName,jdbcType=VARCHAR}, ",
        "#{orderItemProice,jdbcType=DECIMAL}, #{orderItemAmount,jdbcType=INTEGER}, ",
        "#{orderItemUrl,jdbcType=VARCHAR}, #{productId,jdbcType=VARCHAR})"
    })
    int insert(EshopOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_order_item
     *
     * @mbg.generated Wed May 23 10:27:25 CST 2018
     */
    @InsertProvider(type=EshopOrderItemSqlProvider.class, method="insertSelective")
    int insertSelective(EshopOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_order_item
     *
     * @mbg.generated Wed May 23 10:27:25 CST 2018
     */
    @SelectProvider(type=EshopOrderItemSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="is_del", property="isDel", jdbcType=JdbcType.INTEGER),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="order_id", property="orderId", jdbcType=JdbcType.VARCHAR),
        @Result(column="color_id", property="colorId", jdbcType=JdbcType.VARCHAR),
        @Result(column="size_id", property="sizeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="order_item_name", property="orderItemName", jdbcType=JdbcType.VARCHAR),
        @Result(column="order_item_proice", property="orderItemProice", jdbcType=JdbcType.DECIMAL),
        @Result(column="order_item_amount", property="orderItemAmount", jdbcType=JdbcType.INTEGER),
        @Result(column="order_item_url", property="orderItemUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_id", property="productId", jdbcType=JdbcType.VARCHAR)
    })
    List<EshopOrderItem> selectByExample(EshopOrderItemCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_order_item
     *
     * @mbg.generated Wed May 23 10:27:25 CST 2018
     */
    @Select({
        "select",
        "id, is_del, update_time, create_time, order_id, color_id, size_id, order_item_name, ",
        "order_item_proice, order_item_amount, order_item_url, product_id",
        "from eshop_order_item",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="is_del", property="isDel", jdbcType=JdbcType.INTEGER),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="order_id", property="orderId", jdbcType=JdbcType.VARCHAR),
        @Result(column="color_id", property="colorId", jdbcType=JdbcType.VARCHAR),
        @Result(column="size_id", property="sizeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="order_item_name", property="orderItemName", jdbcType=JdbcType.VARCHAR),
        @Result(column="order_item_proice", property="orderItemProice", jdbcType=JdbcType.DECIMAL),
        @Result(column="order_item_amount", property="orderItemAmount", jdbcType=JdbcType.INTEGER),
        @Result(column="order_item_url", property="orderItemUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_id", property="productId", jdbcType=JdbcType.VARCHAR)
    })
    EshopOrderItem selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_order_item
     *
     * @mbg.generated Wed May 23 10:27:25 CST 2018
     */
    @UpdateProvider(type=EshopOrderItemSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") EshopOrderItem record, @Param("example") EshopOrderItemCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_order_item
     *
     * @mbg.generated Wed May 23 10:27:25 CST 2018
     */
    @UpdateProvider(type=EshopOrderItemSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") EshopOrderItem record, @Param("example") EshopOrderItemCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_order_item
     *
     * @mbg.generated Wed May 23 10:27:25 CST 2018
     */
    @UpdateProvider(type=EshopOrderItemSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(EshopOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_order_item
     *
     * @mbg.generated Wed May 23 10:27:25 CST 2018
     */
    @Update({
        "update eshop_order_item",
        "set is_del = #{isDel,jdbcType=INTEGER},",
          "update_time = #{updateTime,jdbcType=DATE},",
          "create_time = #{createTime,jdbcType=DATE},",
          "order_id = #{orderId,jdbcType=VARCHAR},",
          "color_id = #{colorId,jdbcType=VARCHAR},",
          "size_id = #{sizeId,jdbcType=VARCHAR},",
          "order_item_name = #{orderItemName,jdbcType=VARCHAR},",
          "order_item_proice = #{orderItemProice,jdbcType=DECIMAL},",
          "order_item_amount = #{orderItemAmount,jdbcType=INTEGER},",
          "order_item_url = #{orderItemUrl,jdbcType=VARCHAR},",
          "product_id = #{productId,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(EshopOrderItem record);
}